// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using audits_.net_react_ramine.Data;

#nullable disable

namespace audits_.net_react_ramine.Migrations
{
    [DbContext(typeof(AuditsDbContext))]
    [Migration("20221009055424_CreateAuditsTable")]
    partial class CreateAuditsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("audits_.net_react_ramine.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audits");

                    b.ToTable("audits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 415, DateTimeKind.Utc).AddTicks(1695),
                            Event = "authentication:logout",
                            Message = "Dolores ab magni amet ipsa. Reiciendis quos atque sint illum culpa ab autem incidunt. Est dolorum consectetur est sit quo maiores. Quia est sapiente ullam dolorum nostrum dolorem eos quos. Dolore iusto modi incidunt ex et exercitationem.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 415, DateTimeKind.Utc).AddTicks(1695),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 415, DateTimeKind.Utc).AddTicks(6061),
                            Event = "invoice:send",
                            Message = "Et laudantium velit consequatur at sed eius. Voluptatibus nihil debitis libero rem illum alias. Non et eveniet rem inventore porro et. Quia unde sunt deserunt modi. Enim consequatur dolorem nihil velit. Consequatur modi veniam aut est ea perspiciatis et nulla.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 415, DateTimeKind.Utc).AddTicks(6061),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 415, DateTimeKind.Utc).AddTicks(9899),
                            Event = "invoice:create",
                            Message = "Nihil tenetur libero dolorem cum. Eum sit blanditiis sint nisi sit qui. Deserunt sunt eligendi ea harum sunt. Amet reprehenderit repellendus omnis. Ut velit repudiandae minima quos magni nemo sed. Vel pariatur officiis amet sed.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 415, DateTimeKind.Utc).AddTicks(9900),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 416, DateTimeKind.Utc).AddTicks(3427),
                            Event = "settings:change",
                            Message = "Tempore nisi consequatur quo est perferendis soluta. At architecto sapiente esse asperiores. Laudantium corporis commodi laudantium. Quia voluptatum velit sunt aut velit pariatur dolorem laboriosam et. Est dolorem ipsum libero et sed quae corrupti beatae repellendus. Dolorem reiciendis tenetur nihil ipsum.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 416, DateTimeKind.Utc).AddTicks(3427),
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 416, DateTimeKind.Utc).AddTicks(6271),
                            Event = "authentication:new",
                            Message = "Sint nesciunt non sit quod ab est reiciendis hic. Voluptate dolor iste molestias fuga est expedita fuga accusamus. Quidem in perferendis expedita assumenda blanditiis aperiam sint et maxime. Saepe soluta magnam magni id aspernatur est. Earum nemo molestias non dolorem qui ullam adipisci.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 416, DateTimeKind.Utc).AddTicks(6271),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 416, DateTimeKind.Utc).AddTicks(8141),
                            Event = "authentication:new",
                            Message = "Doloribus autem est beatae velit amet. Quisquam cupiditate dolore deleniti iste minima expedita. Qui et autem impedit facilis fugiat reprehenderit cum.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 416, DateTimeKind.Utc).AddTicks(8141),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 417, DateTimeKind.Utc).AddTicks(1071),
                            Event = "invoice:send",
                            Message = "Repudiandae rerum minus delectus. Accusantium voluptates at id. Tempora et quod consequatur ipsum reprehenderit dolorem. Repellendus consequatur nostrum voluptatem illo possimus veritatis voluptas. Nostrum omnis dignissimos provident delectus labore iusto sint doloremque corporis. Itaque praesentium tenetur voluptatem velit aut velit.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 417, DateTimeKind.Utc).AddTicks(1071),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 417, DateTimeKind.Utc).AddTicks(3908),
                            Event = "invoice:create",
                            Message = "Nemo architecto est libero laborum est quia minima quam distinctio. Odio non velit eius sint eaque temporibus facere alias. Earum molestias quia perspiciatis. Nostrum quis quia non ad nihil nostrum temporibus incidunt nihil. Voluptate quo corporis occaecati quia omnis. Voluptatem sed ut consequuntur.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 417, DateTimeKind.Utc).AddTicks(3908),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 417, DateTimeKind.Utc).AddTicks(5901),
                            Event = "invoice:send",
                            Message = "Vel est earum maxime. Qui quis beatae adipisci accusantium esse officia et quia. Praesentium assumenda nihil in id neque sed.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 417, DateTimeKind.Utc).AddTicks(5901),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 417, DateTimeKind.Utc).AddTicks(8670),
                            Event = "invoice:create",
                            Message = "Veniam molestias placeat aut cumque aut. Explicabo earum mollitia quis. Et est dicta autem amet assumenda quasi. Unde veniam ipsa in illum officia qui omnis.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 417, DateTimeKind.Utc).AddTicks(8670),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 418, DateTimeKind.Utc).AddTicks(2830),
                            Event = "authentication:logout",
                            Message = "Et non distinctio deleniti unde dolor expedita nam. Consequatur aut corporis est dolor rem distinctio eius est. Eos voluptatem non in aliquid alias et tempora earum dolor. Cupiditate quo adipisci omnis eos et omnis sunt. Consequatur magnam in molestiae.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 418, DateTimeKind.Utc).AddTicks(2830),
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 418, DateTimeKind.Utc).AddTicks(7251),
                            Event = "authentication:logout",
                            Message = "Nam voluptate omnis molestiae ad sapiente quaerat similique. Minima saepe sed incidunt nesciunt est veritatis. Tempora facere aliquid ex aliquam quidem est possimus quia amet. Sit ipsa optio exercitationem. At id repellat libero numquam nesciunt deserunt beatae. Cupiditate perferendis reiciendis pariatur.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 418, DateTimeKind.Utc).AddTicks(7251),
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 419, DateTimeKind.Utc).AddTicks(8454),
                            Event = "invoice:send",
                            Message = "Sunt explicabo harum et molestias omnis qui. Pariatur quia officiis culpa ut quia temporibus possimus. Adipisci voluptatem consequuntur et alias. Aut eum ad illum quibusdam. Quis consectetur est ut sed voluptatem pariatur. Iusto perspiciatis omnis eum et sed facilis.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 419, DateTimeKind.Utc).AddTicks(8457),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 420, DateTimeKind.Utc).AddTicks(2126),
                            Event = "authentication:logout",
                            Message = "Temporibus ex labore voluptatum qui harum tempora tempora laboriosam sequi. Quod in est animi dolor accusamus quae. Neque eius ut quia. Sit occaecati expedita quam.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 420, DateTimeKind.Utc).AddTicks(2126),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 420, DateTimeKind.Utc).AddTicks(6991),
                            Event = "authentication:new",
                            Message = "Rem ut voluptatum fugit consequatur nulla. Nihil consequatur maxime ut ipsum. Eos voluptatum rerum dolorem illum aut molestiae et quisquam. Necessitatibus enim dolorum dolorem alias. Perspiciatis est totam aut numquam aut. Et aut architecto omnis a est accusamus sed ut ad.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 420, DateTimeKind.Utc).AddTicks(6992),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 420, DateTimeKind.Utc).AddTicks(9889),
                            Event = "invoice:create",
                            Message = "Natus rerum adipisci eligendi. Voluptate velit doloremque nesciunt eveniet architecto iusto est minus. Ipsum qui voluptate enim provident nihil. Velit et porro labore beatae ratione assumenda.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 420, DateTimeKind.Utc).AddTicks(9889),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 421, DateTimeKind.Utc).AddTicks(3765),
                            Event = "authentication:logout",
                            Message = "A veritatis non in eius porro. Porro maiores id cupiditate quia et ut. Id consequuntur et soluta odit. Quidem nostrum molestiae voluptas. Aut voluptatem laborum et quo. Veritatis animi eligendi quis accusamus qui.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 421, DateTimeKind.Utc).AddTicks(3765),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 421, DateTimeKind.Utc).AddTicks(7302),
                            Event = "authentication:new",
                            Message = "Eos officiis provident officia aut provident. Nisi nesciunt maxime rerum. Et corporis enim laboriosam voluptas rerum velit modi. Nobis omnis similique quam reprehenderit. Quasi blanditiis ipsa modi sapiente corporis dolor quod.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 421, DateTimeKind.Utc).AddTicks(7303),
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 422, DateTimeKind.Utc).AddTicks(503),
                            Event = "settings:change",
                            Message = "Quas harum ex distinctio consequatur dolorum amet suscipit alias. Quam veniam ipsa cupiditate ipsum nulla sunt beatae. Iste dolore ratione laudantium consequatur. Neque omnis magnam maiores nobis.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 422, DateTimeKind.Utc).AddTicks(503),
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 422, DateTimeKind.Utc).AddTicks(3700),
                            Event = "authentication:new",
                            Message = "Inventore ut est quis est ratione facere. Dolores ducimus est culpa ipsum rerum aut optio. Fugiat quisquam autem excepturi labore quo quas incidunt et. Quis modi et molestiae dicta. Rem accusantium libero et repudiandae.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 422, DateTimeKind.Utc).AddTicks(3700),
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 422, DateTimeKind.Utc).AddTicks(7664),
                            Event = "invoice:create",
                            Message = "Sed ea odio sequi asperiores iste omnis quidem enim. Sit voluptas doloribus dolores quam. Consequatur aut quia doloribus ad similique ipsam. Debitis ipsa quasi et. Facere dolores aut quaerat nobis quia sit. Consequatur tempora laudantium delectus non libero recusandae.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 422, DateTimeKind.Utc).AddTicks(7664),
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 423, DateTimeKind.Utc).AddTicks(1650),
                            Event = "authentication:logout",
                            Message = "Voluptatem qui voluptate laborum beatae qui at. Dolor ea dolorem non. Qui quia asperiores sed quasi. Ut consectetur sunt ducimus id debitis in nihil vel pariatur. Eos repellat mollitia accusantium ipsum sit voluptatem fuga dolore sunt.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 423, DateTimeKind.Utc).AddTicks(1650),
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 423, DateTimeKind.Utc).AddTicks(5739),
                            Event = "settings:change",
                            Message = "Voluptates ipsum nisi quaerat. Et autem voluptas adipisci quo quos aut totam sit dolores. Adipisci consequatur necessitatibus laboriosam modi cum iusto esse. Praesentium molestiae natus explicabo. Consequatur omnis omnis inventore aperiam facere ullam et itaque at.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 423, DateTimeKind.Utc).AddTicks(5740),
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 423, DateTimeKind.Utc).AddTicks(8042),
                            Event = "authentication:logout",
                            Message = "Et quae autem consequatur expedita qui. Beatae dolores quaerat qui exercitationem ea blanditiis ut et dicta. Ipsum ut facere perspiciatis eligendi.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 423, DateTimeKind.Utc).AddTicks(8042),
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 424, DateTimeKind.Utc).AddTicks(1327),
                            Event = "settings:change",
                            Message = "Ad sint commodi voluptatem fuga minima officiis ut. Voluptatem rerum quasi laborum est incidunt ducimus. Nobis est dolor tempore incidunt quas. Cupiditate quia repudiandae aut voluptas nesciunt et ea perferendis.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 424, DateTimeKind.Utc).AddTicks(1327),
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 424, DateTimeKind.Utc).AddTicks(4717),
                            Event = "authentication:new",
                            Message = "Iste et ut corrupti quo et. Ut rerum perferendis aut vel architecto aut suscipit non. Possimus et cum iure vel ipsum. Aut ut accusamus consequatur saepe ut quidem eveniet soluta.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 424, DateTimeKind.Utc).AddTicks(4719),
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 424, DateTimeKind.Utc).AddTicks(8318),
                            Event = "invoice:create",
                            Message = "Qui quae earum praesentium et sunt itaque optio qui quia. Sapiente unde et optio fuga nam. Aut sequi culpa non ut. Ducimus nobis quia aperiam. Ratione magnam sint vel consequuntur commodi quidem laudantium.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 424, DateTimeKind.Utc).AddTicks(8318),
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 425, DateTimeKind.Utc).AddTicks(4033),
                            Event = "invoice:send",
                            Message = "At doloremque omnis suscipit porro. Sit praesentium architecto non sed et libero. Voluptates et reiciendis harum. Quos ea excepturi voluptatem nihil sit qui et est deserunt. Sunt vitae qui porro et laborum tempore inventore nemo officiis. Voluptatum in consequatur expedita porro et veritatis id rerum et.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 425, DateTimeKind.Utc).AddTicks(4034),
                            UserId = 1
                        },
                        new
                        {
                            Id = 29,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 425, DateTimeKind.Utc).AddTicks(7835),
                            Event = "authentication:new",
                            Message = "Error et ut quis enim quia. Architecto repellat inventore facilis provident nihil ullam sapiente incidunt minima. Odit beatae dolor alias quia laudantium quia et et placeat. Dolore non aspernatur itaque reiciendis ut nam.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 425, DateTimeKind.Utc).AddTicks(7836),
                            UserId = 2
                        },
                        new
                        {
                            Id = 30,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 426, DateTimeKind.Utc).AddTicks(2343),
                            Event = "invoice:send",
                            Message = "Maiores accusamus et ratione quia blanditiis dolor ratione nulla ad. Autem voluptatem possimus et eveniet ducimus. Reprehenderit id asperiores at magnam minus sed. Doloremque aut natus quasi numquam repellat placeat cumque. Beatae sunt corrupti non doloremque consequuntur asperiores.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 426, DateTimeKind.Utc).AddTicks(2344),
                            UserId = 1
                        },
                        new
                        {
                            Id = 31,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 426, DateTimeKind.Utc).AddTicks(7009),
                            Event = "invoice:send",
                            Message = "Fugit iste est esse rem consequatur optio. Tenetur vero cupiditate non amet velit aliquid praesentium magnam ut. Quis quis labore tempore qui corporis alias. Doloribus facere omnis debitis. Veniam tempora non necessitatibus quae quia. Odio facere quo sed.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 426, DateTimeKind.Utc).AddTicks(7010),
                            UserId = 1
                        },
                        new
                        {
                            Id = 32,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 427, DateTimeKind.Utc).AddTicks(1185),
                            Event = "authentication:logout",
                            Message = "Dolores qui repudiandae dolor. Dolorem distinctio assumenda ut totam repudiandae sit. Blanditiis sequi temporibus dignissimos sint ducimus et vel. Ut id maiores minima. Sit nobis nulla excepturi aspernatur placeat dolores. Et quia error eligendi doloremque numquam.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 427, DateTimeKind.Utc).AddTicks(1186),
                            UserId = 1
                        },
                        new
                        {
                            Id = 33,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 427, DateTimeKind.Utc).AddTicks(5650),
                            Event = "invoice:create",
                            Message = "Ullam soluta corporis odit. Adipisci doloremque nostrum laboriosam eaque quaerat. Sed aliquam et laudantium est iusto. Molestiae rerum amet ut quia qui pariatur quia eum. Consequatur dolorum aperiam maiores et debitis qui inventore. Atque aliquam ex ipsum.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 427, DateTimeKind.Utc).AddTicks(5653),
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 427, DateTimeKind.Utc).AddTicks(7883),
                            Event = "invoice:send",
                            Message = "Quis repudiandae nesciunt eligendi ipsum soluta. Eum ab sunt fugit iusto dicta ut blanditiis ducimus. Ut odit iste cupiditate aut.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 427, DateTimeKind.Utc).AddTicks(7883),
                            UserId = 2
                        },
                        new
                        {
                            Id = 35,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 428, DateTimeKind.Utc).AddTicks(3120),
                            Event = "authentication:new",
                            Message = "Consequatur ipsum aut et et nisi voluptatum. Numquam incidunt aut qui ullam numquam corporis quod est esse. Aut dolorem enim voluptatem sunt et sequi est. Consectetur eum qui expedita sunt voluptatem. Non impedit beatae libero. Veritatis fuga omnis recusandae dolor expedita et quibusdam soluta.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 428, DateTimeKind.Utc).AddTicks(3120),
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 428, DateTimeKind.Utc).AddTicks(6639),
                            Event = "settings:change",
                            Message = "Voluptates itaque quidem enim magni. Veniam provident consequatur omnis est. Vel qui voluptates et alias quos perferendis. Ex reprehenderit suscipit vel. Molestiae dolores sequi enim porro ad quis debitis.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 428, DateTimeKind.Utc).AddTicks(6639),
                            UserId = 1
                        },
                        new
                        {
                            Id = 37,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 429, DateTimeKind.Utc).AddTicks(2260),
                            Event = "invoice:create",
                            Message = "Rem enim magni fuga ratione. Quibusdam molestiae ut quia enim blanditiis qui tenetur. Autem fuga a dolorum labore repellendus ratione magnam rerum. Animi fuga eius dolorem voluptatem quia illum distinctio corporis unde. Ex voluptas minima ea et mollitia. Culpa quibusdam illum ut et non nemo nemo rerum.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 429, DateTimeKind.Utc).AddTicks(2261),
                            UserId = 1
                        },
                        new
                        {
                            Id = 38,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 429, DateTimeKind.Utc).AddTicks(8120),
                            Event = "invoice:send",
                            Message = "Amet possimus cumque rerum soluta omnis magnam ut magni rerum. Quia expedita officia nostrum minus cumque nemo deserunt eius. Nam sit voluptatem quis consequatur nesciunt eius molestiae ut dolores. Consequatur quod debitis suscipit qui quae earum magnam quam. Recusandae voluptas consequatur exercitationem provident porro. Et ea qui accusamus neque temporibus.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 429, DateTimeKind.Utc).AddTicks(8120),
                            UserId = 1
                        },
                        new
                        {
                            Id = 39,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 430, DateTimeKind.Utc).AddTicks(2554),
                            Event = "invoice:create",
                            Message = "Consequatur autem officia exercitationem. Occaecati expedita quod modi est commodi. Qui a quis hic sed perferendis est alias aliquam quidem. Est rerum ut aut libero eius. Nobis tempore maxime corrupti. Ut doloribus repudiandae eaque fugiat excepturi recusandae.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 430, DateTimeKind.Utc).AddTicks(2554),
                            UserId = 1
                        },
                        new
                        {
                            Id = 40,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 430, DateTimeKind.Utc).AddTicks(6661),
                            Event = "invoice:send",
                            Message = "Quasi dolorem non repudiandae saepe vitae ipsa architecto. Impedit explicabo reprehenderit iure voluptate. Aut voluptatem qui tempore sunt vitae aliquam minima. Cupiditate sint placeat eos voluptatum nam. Dolorem minima repudiandae voluptatibus doloribus aliquam est corrupti animi.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 430, DateTimeKind.Utc).AddTicks(6662),
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 431, DateTimeKind.Utc).AddTicks(323),
                            Event = "invoice:create",
                            Message = "Quae vel ut laborum. Autem dicta consectetur sit sit ipsam saepe cum. Est dolor nihil molestiae sit sint quis quia minus. Excepturi distinctio enim ipsam recusandae vitae quae itaque. Temporibus voluptas nihil iure.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 431, DateTimeKind.Utc).AddTicks(324),
                            UserId = 1
                        },
                        new
                        {
                            Id = 42,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 431, DateTimeKind.Utc).AddTicks(4316),
                            Event = "authentication:new",
                            Message = "Consequatur quia voluptatem et eos. Ipsa necessitatibus quisquam harum aliquid quia. Et harum labore fugit vel doloribus consequatur esse tempora omnis. Distinctio est est ratione autem sit tempora. Sint beatae quis quaerat qui consequuntur dolor.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 431, DateTimeKind.Utc).AddTicks(4317),
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 431, DateTimeKind.Utc).AddTicks(7014),
                            Event = "invoice:create",
                            Message = "Voluptatem ratione aperiam quidem quia aspernatur aut. Expedita consectetur aut repellat eveniet sed. Non soluta perspiciatis quos inventore nemo pariatur est autem deleniti.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 431, DateTimeKind.Utc).AddTicks(7015),
                            UserId = 2
                        },
                        new
                        {
                            Id = 44,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 432, DateTimeKind.Utc).AddTicks(1002),
                            Event = "authentication:logout",
                            Message = "Error nihil ipsam animi magni. Qui voluptas officia facere sint quia vel quam. Repudiandae quis aut sunt quo ratione et possimus minima. Quo error dolores sint. Nulla dolor aut illum at error quos est possimus.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 432, DateTimeKind.Utc).AddTicks(1003),
                            UserId = 2
                        },
                        new
                        {
                            Id = 45,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 432, DateTimeKind.Utc).AddTicks(4236),
                            Event = "settings:change",
                            Message = "Voluptatibus quo ut quia deserunt ea sit dignissimos quasi. Tempore molestias magni quo atque fuga perferendis placeat eum voluptatem. Molestiae molestiae tempore ullam. Consectetur necessitatibus et dolore aperiam.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 432, DateTimeKind.Utc).AddTicks(4237),
                            UserId = 2
                        },
                        new
                        {
                            Id = 46,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 432, DateTimeKind.Utc).AddTicks(7844),
                            Event = "invoice:create",
                            Message = "Excepturi reiciendis et aut maxime. Eaque minus ipsam suscipit. Ut aperiam et nemo. Odio repudiandae ducimus inventore cumque minus expedita nemo. Ea nobis aliquid distinctio facilis tenetur. Eos ut eum ipsum consequuntur.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 432, DateTimeKind.Utc).AddTicks(7844),
                            UserId = 1
                        },
                        new
                        {
                            Id = 47,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 433, DateTimeKind.Utc).AddTicks(1881),
                            Event = "invoice:send",
                            Message = "Voluptatem a quidem temporibus quos ducimus voluptatem sed. Et officiis sed animi. Alias tempora quo repellendus voluptates. Odit sint veritatis ea qui culpa repellendus. Aliquam rem expedita molestiae aut accusantium. Repellat cumque voluptatibus a quia veniam.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 433, DateTimeKind.Utc).AddTicks(1882),
                            UserId = 2
                        },
                        new
                        {
                            Id = 48,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 433, DateTimeKind.Utc).AddTicks(5322),
                            Event = "authentication:new",
                            Message = "Ipsa praesentium facilis non consequatur et nihil alias. Sapiente voluptates numquam numquam. Perspiciatis eum ut autem. Quia cupiditate saepe veniam ipsa repellat numquam omnis voluptatem.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 433, DateTimeKind.Utc).AddTicks(5323),
                            UserId = 1
                        },
                        new
                        {
                            Id = 49,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 433, DateTimeKind.Utc).AddTicks(8352),
                            Event = "invoice:create",
                            Message = "Consectetur harum a odio optio non dolor similique cupiditate. Ullam veniam suscipit repellendus omnis repellat recusandae voluptas. Quod odio perspiciatis perferendis quos nemo accusantium.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 433, DateTimeKind.Utc).AddTicks(8353),
                            UserId = 1
                        },
                        new
                        {
                            Id = 50,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 434, DateTimeKind.Utc).AddTicks(1539),
                            Event = "authentication:new",
                            Message = "Rerum dolores modi voluptatum dicta dolor. Possimus id inventore nulla quis est beatae laudantium consequatur. Unde culpa autem ea accusantium id qui. Necessitatibus sunt ea rerum possimus magni.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 434, DateTimeKind.Utc).AddTicks(1540),
                            UserId = 2
                        },
                        new
                        {
                            Id = 51,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 434, DateTimeKind.Utc).AddTicks(3375),
                            Event = "invoice:create",
                            Message = "Ea praesentium quos veritatis quia. Atque vel odit ea sit. Voluptates ullam iste distinctio cum totam.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 434, DateTimeKind.Utc).AddTicks(3375),
                            UserId = 2
                        },
                        new
                        {
                            Id = 52,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 434, DateTimeKind.Utc).AddTicks(7324),
                            Event = "invoice:send",
                            Message = "Sequi sint perspiciatis cupiditate. Totam sunt delectus quis enim. Illum quia quae iste placeat aut eos dolor. Et provident tempora cum adipisci ut tempora. Sit quia incidunt saepe quidem natus. Quas accusamus omnis minima consectetur.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 434, DateTimeKind.Utc).AddTicks(7324),
                            UserId = 1
                        },
                        new
                        {
                            Id = 53,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 435, DateTimeKind.Utc).AddTicks(1056),
                            Event = "authentication:logout",
                            Message = "Sit qui ea iusto. Ullam debitis voluptatem vitae eos cumque corporis. Voluptatem impedit quidem quas porro deleniti. Et eius eveniet necessitatibus eum beatae non repellat. Animi temporibus et doloremque similique magnam ex vel.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 435, DateTimeKind.Utc).AddTicks(1057),
                            UserId = 2
                        },
                        new
                        {
                            Id = 54,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 435, DateTimeKind.Utc).AddTicks(7234),
                            Event = "authentication:logout",
                            Message = "Libero voluptatibus culpa velit eaque suscipit. Sunt eos facere perferendis dolores accusantium omnis excepturi aut. Voluptate ratione impedit qui et provident aut incidunt iste. Placeat quo iure quaerat quia quae est deserunt tempore. Saepe et quia est qui non nemo. Eos repellat voluptatem cumque nobis aut molestiae eum.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 435, DateTimeKind.Utc).AddTicks(7235),
                            UserId = 1
                        },
                        new
                        {
                            Id = 55,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 436, DateTimeKind.Utc).AddTicks(697),
                            Event = "authentication:new",
                            Message = "Molestias veritatis non ex perspiciatis aperiam rerum consequatur rerum. Doloremque dolores ea cum libero molestiae at. Voluptatem dolores blanditiis velit ex consequatur quis laudantium.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 436, DateTimeKind.Utc).AddTicks(698),
                            UserId = 1
                        },
                        new
                        {
                            Id = 56,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 436, DateTimeKind.Utc).AddTicks(5319),
                            Event = "authentication:new",
                            Message = "Quae sint quam iste. Optio incidunt est atque quaerat amet doloribus. Deserunt aut pariatur qui expedita voluptates. Et voluptatem tempora necessitatibus nisi sint quam qui. Numquam soluta ut quia perspiciatis. Quidem harum asperiores voluptas quod quia ut.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 436, DateTimeKind.Utc).AddTicks(5320),
                            UserId = 2
                        },
                        new
                        {
                            Id = 57,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 436, DateTimeKind.Utc).AddTicks(8210),
                            Event = "authentication:logout",
                            Message = "Eos incidunt numquam enim alias. Deleniti id ducimus sit quisquam voluptatem ratione. Error sed qui officiis cupiditate tempora molestias distinctio voluptas. Eos numquam repudiandae aut.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 436, DateTimeKind.Utc).AddTicks(8210),
                            UserId = 1
                        },
                        new
                        {
                            Id = 58,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 437, DateTimeKind.Utc).AddTicks(3143),
                            Event = "authentication:new",
                            Message = "Qui distinctio est impedit totam eum eveniet. Maiores consequuntur sunt velit neque ipsam eaque id iure. Minima ratione numquam exercitationem aut quae aut. Atque vel vitae qui maiores temporibus. Consequatur dolore consectetur voluptatem qui dignissimos vel. Ipsum odio labore optio eveniet impedit voluptas.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 437, DateTimeKind.Utc).AddTicks(3143),
                            UserId = 2
                        },
                        new
                        {
                            Id = 59,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 437, DateTimeKind.Utc).AddTicks(6460),
                            Event = "authentication:logout",
                            Message = "Hic nam dolor atque aut sed beatae expedita optio. Cum iste fuga est. Non sed maiores quidem qui mollitia iusto voluptatem. Quaerat sint magni vero perferendis eius aut.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 437, DateTimeKind.Utc).AddTicks(6461),
                            UserId = 1
                        },
                        new
                        {
                            Id = 60,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 437, DateTimeKind.Utc).AddTicks(9359),
                            Event = "invoice:send",
                            Message = "Omnis ut rerum est. Quo quam fugiat cupiditate voluptatem iure aut fugiat repellat asperiores. Fuga tempore id eligendi assumenda. Debitis consequatur modi officia corrupti quo accusantium.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 437, DateTimeKind.Utc).AddTicks(9359),
                            UserId = 2
                        },
                        new
                        {
                            Id = 61,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 438, DateTimeKind.Utc).AddTicks(1985),
                            Event = "settings:change",
                            Message = "Harum facilis delectus nam optio. Modi veniam voluptatibus sunt quisquam voluptatem nemo velit mollitia at. Accusantium rem error exercitationem distinctio voluptatem quo illum.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 438, DateTimeKind.Utc).AddTicks(1986),
                            UserId = 1
                        },
                        new
                        {
                            Id = 62,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 438, DateTimeKind.Utc).AddTicks(4623),
                            Event = "invoice:create",
                            Message = "Nulla quo quaerat id. Doloremque neque ut dignissimos in et ullam rerum. Voluptas et aliquam corporis non qui. Eligendi quaerat magnam dolore.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 438, DateTimeKind.Utc).AddTicks(4623),
                            UserId = 2
                        },
                        new
                        {
                            Id = 63,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 438, DateTimeKind.Utc).AddTicks(6966),
                            Event = "invoice:send",
                            Message = "Recusandae autem nemo quis laboriosam repellendus omnis labore aut voluptas. Placeat reprehenderit molestiae similique eligendi tempora nobis. In vitae voluptatem rem.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 438, DateTimeKind.Utc).AddTicks(6966),
                            UserId = 1
                        },
                        new
                        {
                            Id = 64,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 438, DateTimeKind.Utc).AddTicks(9750),
                            Event = "authentication:logout",
                            Message = "Maxime suscipit aut sed repellat ea. Molestiae neque cupiditate quia voluptas aut consequatur ut. Nostrum voluptas perspiciatis similique distinctio quia odio. Sint molestias non voluptas.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 438, DateTimeKind.Utc).AddTicks(9751),
                            UserId = 1
                        },
                        new
                        {
                            Id = 65,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 439, DateTimeKind.Utc).AddTicks(2187),
                            Event = "authentication:logout",
                            Message = "Qui enim illum non accusamus sit non. Eum suscipit omnis modi consequatur saepe et necessitatibus dicta. Ex dicta expedita quis consectetur.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 439, DateTimeKind.Utc).AddTicks(2188),
                            UserId = 1
                        },
                        new
                        {
                            Id = 66,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 439, DateTimeKind.Utc).AddTicks(4436),
                            Event = "authentication:new",
                            Message = "Eos sit non ipsa provident. Exercitationem cum quos impedit vel qui qui doloremque. Animi repellendus unde non ea.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 439, DateTimeKind.Utc).AddTicks(4437),
                            UserId = 2
                        },
                        new
                        {
                            Id = 67,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 439, DateTimeKind.Utc).AddTicks(6825),
                            Event = "settings:change",
                            Message = "Perspiciatis quo excepturi cupiditate possimus ducimus modi et exercitationem. Libero ut consequatur autem. Sed libero qui qui voluptas ipsum qui velit.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 439, DateTimeKind.Utc).AddTicks(6826),
                            UserId = 2
                        },
                        new
                        {
                            Id = 68,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 440, DateTimeKind.Utc).AddTicks(963),
                            Event = "settings:change",
                            Message = "Et consequatur dolor distinctio velit illo aspernatur est. Amet quibusdam qui at dolorem. Sint eos maiores necessitatibus. Dolorem sunt at perferendis eos eaque tempore perspiciatis quis. Enim optio ipsam exercitationem consequatur optio sit quia voluptatem est. Consequatur distinctio id est.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 440, DateTimeKind.Utc).AddTicks(964),
                            UserId = 1
                        },
                        new
                        {
                            Id = 69,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 440, DateTimeKind.Utc).AddTicks(3504),
                            Event = "settings:change",
                            Message = "Maiores voluptas ab quisquam voluptatibus ad. Dolores rem eligendi quia voluptas cum hic. Adipisci perspiciatis dolorum vitae nostrum quo. Occaecati reiciendis corporis nobis perferendis quam sit consequuntur. Qui et nemo odio ut impedit. Consequatur facilis accusamus id quaerat fugit quia.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 440, DateTimeKind.Utc).AddTicks(3504),
                            UserId = 2
                        },
                        new
                        {
                            Id = 70,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 440, DateTimeKind.Utc).AddTicks(4821),
                            Event = "authentication:logout",
                            Message = "Nihil laborum ipsum eius. Suscipit eos eos est odio ratione asperiores. Unde deserunt et vel dignissimos delectus commodi a numquam amet.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 440, DateTimeKind.Utc).AddTicks(4821),
                            UserId = 2
                        },
                        new
                        {
                            Id = 71,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 440, DateTimeKind.Utc).AddTicks(6269),
                            Event = "invoice:create",
                            Message = "Ab cupiditate deleniti sed pariatur porro in. Voluptas assumenda voluptatem molestias suscipit molestiae veritatis dolorem. Temporibus optio commodi omnis porro dolorem ut rerum.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 440, DateTimeKind.Utc).AddTicks(6269),
                            UserId = 2
                        },
                        new
                        {
                            Id = 72,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 440, DateTimeKind.Utc).AddTicks(8977),
                            Event = "authentication:logout",
                            Message = "Cumque iusto asperiores in aut aut aspernatur. Similique qui vitae et facere aut aperiam occaecati quia. Dolorem architecto est et blanditiis quos nihil. Quo dolor est voluptas dolorem aut quo hic quisquam cum. Ut dicta at omnis est magnam omnis.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 440, DateTimeKind.Utc).AddTicks(8977),
                            UserId = 2
                        },
                        new
                        {
                            Id = 73,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 441, DateTimeKind.Utc).AddTicks(1926),
                            Event = "authentication:new",
                            Message = "Numquam quod laborum enim. Officia et recusandae eos debitis qui provident delectus. Quae rerum non aliquid quia. Numquam commodi ex nam magnam assumenda ex commodi laboriosam.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 441, DateTimeKind.Utc).AddTicks(1926),
                            UserId = 2
                        },
                        new
                        {
                            Id = 74,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 441, DateTimeKind.Utc).AddTicks(4659),
                            Event = "authentication:logout",
                            Message = "Et veniam voluptatem dignissimos autem debitis fugiat eaque. Tempore magni qui mollitia libero odit sit. Odit quaerat suscipit quo.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 441, DateTimeKind.Utc).AddTicks(4659),
                            UserId = 2
                        },
                        new
                        {
                            Id = 75,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 441, DateTimeKind.Utc).AddTicks(7289),
                            Event = "authentication:new",
                            Message = "In reiciendis saepe saepe fuga repudiandae. Libero quidem incidunt suscipit ipsam. Soluta error quos animi saepe alias illo.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 441, DateTimeKind.Utc).AddTicks(7289),
                            UserId = 2
                        },
                        new
                        {
                            Id = 76,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 442, DateTimeKind.Utc).AddTicks(450),
                            Event = "invoice:create",
                            Message = "Minus dolorum consectetur a voluptatem. Praesentium eum velit earum eos iure. Non repellendus non sint dicta quidem et. Exercitationem voluptas sed ut omnis.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 442, DateTimeKind.Utc).AddTicks(450),
                            UserId = 2
                        },
                        new
                        {
                            Id = 77,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 442, DateTimeKind.Utc).AddTicks(5902),
                            Event = "invoice:send",
                            Message = "Ut eos aut perspiciatis recusandae fugiat. Iste dignissimos consequatur praesentium dolore aperiam consectetur. Aspernatur in blanditiis eos ut quibusdam. Officiis quo velit corporis quia facilis aliquam. Tempora doloribus non ut beatae.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 442, DateTimeKind.Utc).AddTicks(5904),
                            UserId = 1
                        },
                        new
                        {
                            Id = 78,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 442, DateTimeKind.Utc).AddTicks(9318),
                            Event = "authentication:logout",
                            Message = "Est molestias explicabo et omnis sequi sunt sapiente qui. Facere et iusto tempora consequatur iure. Omnis provident facere facere. Tempore numquam ut quas tenetur. Ea iusto molestias culpa natus.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 442, DateTimeKind.Utc).AddTicks(9319),
                            UserId = 1
                        },
                        new
                        {
                            Id = 79,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 443, DateTimeKind.Utc).AddTicks(2190),
                            Event = "invoice:create",
                            Message = "Aut in mollitia aut possimus suscipit voluptate voluptas. Inventore eligendi quod est sed error totam. Voluptatem exercitationem architecto iusto deserunt delectus aliquam incidunt et culpa.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 443, DateTimeKind.Utc).AddTicks(2190),
                            UserId = 2
                        },
                        new
                        {
                            Id = 80,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 443, DateTimeKind.Utc).AddTicks(5574),
                            Event = "authentication:new",
                            Message = "In eum magnam voluptates autem sint. Veritatis omnis voluptatem asperiores est quas et. Placeat quia sint dignissimos vel enim ea. Ullam ab molestias soluta dolores ut aspernatur debitis odio voluptatem.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 443, DateTimeKind.Utc).AddTicks(5575),
                            UserId = 1
                        },
                        new
                        {
                            Id = 81,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 443, DateTimeKind.Utc).AddTicks(9085),
                            Event = "settings:change",
                            Message = "Sint eveniet eligendi quia quia. Ut explicabo sed aut maiores. Ipsam veniam voluptatem labore nihil architecto. Nesciunt incidunt labore inventore porro ad temporibus pariatur expedita numquam. Natus maxime qui est sunt illum at minus et. Similique modi non exercitationem numquam nostrum architecto possimus ducimus.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 443, DateTimeKind.Utc).AddTicks(9086),
                            UserId = 1
                        },
                        new
                        {
                            Id = 82,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 444, DateTimeKind.Utc).AddTicks(1352),
                            Event = "authentication:logout",
                            Message = "Aut adipisci atque ut. Eveniet perspiciatis ab tempore esse ad. Harum eum earum sapiente soluta quo ut eaque. Suscipit ullam quas officiis commodi vel autem corporis. Repellat voluptatem quis aut aliquid et pariatur vero quia quod.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 444, DateTimeKind.Utc).AddTicks(1353),
                            UserId = 1
                        },
                        new
                        {
                            Id = 83,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 444, DateTimeKind.Utc).AddTicks(3832),
                            Event = "invoice:send",
                            Message = "Cumque et et qui porro eaque aut facere rerum explicabo. Aliquam quod fugiat incidunt iusto culpa quo delectus sed rerum. Et quo aut ex ipsum. Ut maxime perspiciatis accusamus fugit suscipit necessitatibus facere optio optio. Tempore nobis quis doloremque.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 444, DateTimeKind.Utc).AddTicks(3833),
                            UserId = 1
                        },
                        new
                        {
                            Id = 84,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 444, DateTimeKind.Utc).AddTicks(8660),
                            Event = "settings:change",
                            Message = "Illo sed eligendi occaecati commodi. Asperiores at rem dolor libero in explicabo non. Laudantium ducimus et reiciendis iste delectus corporis amet. Ad temporibus repellendus maiores maiores excepturi fuga deleniti. Voluptatem et cumque ut aut voluptate natus et libero.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 444, DateTimeKind.Utc).AddTicks(8661),
                            UserId = 1
                        },
                        new
                        {
                            Id = 85,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 445, DateTimeKind.Utc).AddTicks(2629),
                            Event = "invoice:create",
                            Message = "Natus voluptate aliquid et officia beatae molestias et. Rerum libero quibusdam assumenda sunt eos est architecto vel. Eum voluptatem et illo consequuntur dicta consequatur. Qui est sed aspernatur. Sint quia repudiandae quasi nihil non et.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 445, DateTimeKind.Utc).AddTicks(2629),
                            UserId = 2
                        },
                        new
                        {
                            Id = 86,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 445, DateTimeKind.Utc).AddTicks(6346),
                            Event = "invoice:create",
                            Message = "Aut et non quod. Quo deleniti unde autem voluptates eos enim non. Est qui fugiat cumque. Quod quia ut impedit modi saepe blanditiis. Quisquam molestias voluptas est.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 445, DateTimeKind.Utc).AddTicks(6347),
                            UserId = 2
                        },
                        new
                        {
                            Id = 87,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 446, DateTimeKind.Utc).AddTicks(2189),
                            Event = "invoice:send",
                            Message = "Sed debitis perferendis laudantium. Qui odio aspernatur quia aut totam et adipisci. Voluptatibus ex velit aut adipisci impedit sint molestiae ut ullam. Et qui ad sunt numquam quis voluptatem doloremque aperiam. Dignissimos est unde veniam rerum. Rerum sed est similique consequatur suscipit.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 446, DateTimeKind.Utc).AddTicks(2190),
                            UserId = 2
                        },
                        new
                        {
                            Id = 88,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 446, DateTimeKind.Utc).AddTicks(4844),
                            Event = "authentication:logout",
                            Message = "Et et saepe expedita. Itaque velit explicabo recusandae itaque hic fugiat et. Voluptatem ex sint fugiat sequi aut. Saepe in explicabo voluptatem ea.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 446, DateTimeKind.Utc).AddTicks(4844),
                            UserId = 2
                        },
                        new
                        {
                            Id = 89,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 446, DateTimeKind.Utc).AddTicks(8027),
                            Event = "authentication:logout",
                            Message = "Eveniet id nesciunt iste repellat rerum autem doloremque. Qui velit voluptatem aut dolorum animi voluptas minus aut. Assumenda quisquam in non quo ad voluptatem quo quam aperiam.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 446, DateTimeKind.Utc).AddTicks(8028),
                            UserId = 2
                        },
                        new
                        {
                            Id = 90,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 447, DateTimeKind.Utc).AddTicks(630),
                            Event = "settings:change",
                            Message = "Quo officiis consectetur tempora. Ut totam sint consequuntur iure alias qui est. Architecto temporibus consequuntur blanditiis aspernatur. Nostrum ipsam sapiente voluptatem enim. Delectus aut consequatur consequatur consequatur suscipit id.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 447, DateTimeKind.Utc).AddTicks(630),
                            UserId = 1
                        },
                        new
                        {
                            Id = 91,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 447, DateTimeKind.Utc).AddTicks(3025),
                            Event = "authentication:logout",
                            Message = "Laudantium ea dolor molestias. Quidem quo quia aut tenetur ducimus non. Maxime asperiores qui reprehenderit consequatur dolor. Doloremque quo aut veritatis saepe eligendi. Est nam dolore deserunt neque ut sed voluptatem autem necessitatibus. Assumenda quae sed quidem corrupti.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 447, DateTimeKind.Utc).AddTicks(3026),
                            UserId = 2
                        },
                        new
                        {
                            Id = 92,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 447, DateTimeKind.Utc).AddTicks(4198),
                            Event = "authentication:new",
                            Message = "Ex voluptatem non animi. Consequatur ad deleniti explicabo quas suscipit aliquam. Quidem quam dicta et nisi voluptatem.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 447, DateTimeKind.Utc).AddTicks(4199),
                            UserId = 1
                        },
                        new
                        {
                            Id = 93,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 447, DateTimeKind.Utc).AddTicks(8064),
                            Event = "authentication:new",
                            Message = "Unde quisquam est et dignissimos qui quae ipsa at molestiae. Numquam voluptatem non velit porro aperiam hic sit. Doloremque nostrum natus ut ratione aut illo et aliquam et. Quo aspernatur quam vitae iste enim.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 447, DateTimeKind.Utc).AddTicks(8064),
                            UserId = 2
                        },
                        new
                        {
                            Id = 94,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 448, DateTimeKind.Utc).AddTicks(1134),
                            Event = "invoice:send",
                            Message = "Voluptate assumenda quia dolorem sint. Nihil voluptatum vero itaque et. Minima illum rerum temporibus et odit quidem aliquam. Et eaque cum eligendi cumque iste ducimus ipsa cum.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 448, DateTimeKind.Utc).AddTicks(1134),
                            UserId = 2
                        },
                        new
                        {
                            Id = 95,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 448, DateTimeKind.Utc).AddTicks(3485),
                            Event = "invoice:create",
                            Message = "Itaque et non ea. Accusantium aut enim voluptatum et omnis unde beatae. Nihil quod aut et. Beatae tempore consequatur qui.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 448, DateTimeKind.Utc).AddTicks(3485),
                            UserId = 2
                        },
                        new
                        {
                            Id = 96,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 448, DateTimeKind.Utc).AddTicks(5325),
                            Event = "invoice:create",
                            Message = "Corrupti sit magnam ut. Voluptatem rem dolorum dolor aut labore officiis eos. Consectetur velit qui omnis.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 448, DateTimeKind.Utc).AddTicks(5325),
                            UserId = 2
                        },
                        new
                        {
                            Id = 97,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 448, DateTimeKind.Utc).AddTicks(7884),
                            Event = "invoice:create",
                            Message = "Nihil quisquam occaecati corporis est. Dolorum officia sit officiis nam adipisci omnis recusandae ut. Cupiditate et laboriosam sint labore. Veniam molestias incidunt distinctio officiis explicabo perferendis facere. Rerum magnam animi est provident nisi excepturi et omnis.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 448, DateTimeKind.Utc).AddTicks(7884),
                            UserId = 1
                        },
                        new
                        {
                            Id = 98,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 448, DateTimeKind.Utc).AddTicks(9213),
                            Event = "invoice:create",
                            Message = "Veniam unde dolor sed consectetur. Atque nam omnis omnis aut ut nam. In inventore ipsa magnam ut corrupti libero soluta rerum.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 448, DateTimeKind.Utc).AddTicks(9213),
                            UserId = 1
                        },
                        new
                        {
                            Id = 99,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 449, DateTimeKind.Utc).AddTicks(1997),
                            Event = "authentication:logout",
                            Message = "Nobis debitis et et cumque est fugiat quo. Qui odit et delectus. Culpa voluptatibus quod possimus eos dicta sequi est dolor suscipit. Labore aut quia ea voluptate. Ad et in quia et ab et qui id aut. Accusantium sed ut beatae ut et.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 449, DateTimeKind.Utc).AddTicks(1997),
                            UserId = 2
                        },
                        new
                        {
                            Id = 100,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 449, DateTimeKind.Utc).AddTicks(5741),
                            Event = "authentication:logout",
                            Message = "Molestiae quae et est sunt ipsa saepe. Est qui iure quod impedit modi. Fugiat hic eos explicabo. Cumque ipsa assumenda non sit ad modi. Et dignissimos nesciunt inventore.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 449, DateTimeKind.Utc).AddTicks(5742),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("audits_.net_react_ramine.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 412, DateTimeKind.Utc).AddTicks(758),
                            Description = "Et cumque autem et. Recusandae atque labore a non laudantium sit voluptas. Pariatur architecto quibusdam natus repudiandae sapiente earum itaque eaque dicta. Consequatur ab cumque soluta reiciendis. Laborum voluptate voluptate ut aut cupiditate quasi. Quam veniam consequuntur est adipisci qui aut.",
                            OwnerId = 1,
                            Title = "Self-enabling human-resource process improvement",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 412, DateTimeKind.Utc).AddTicks(759)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 412, DateTimeKind.Utc).AddTicks(5223),
                            Description = "Qui odio sit expedita quae. Ad et fuga ullam quos aut quisquam illum temporibus quis. Doloribus odio vel dignissimos debitis illum sed sunt. Voluptatem quasi quod ipsa adipisci occaecati nostrum. Velit ex enim laborum libero voluptas ut qui aut maxime. Voluptatum et veniam quas et.",
                            OwnerId = 2,
                            Title = "Virtual disintermediate projection",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 412, DateTimeKind.Utc).AddTicks(5223)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 412, DateTimeKind.Utc).AddTicks(9083),
                            Description = "Voluptas consectetur molestiae et adipisci quaerat aut nobis maiores voluptatem. Omnis odio quas minus magni maiores iste quia id saepe. Est et vel sapiente officiis adipisci maiores qui a. Placeat quos aut quos sunt.",
                            OwnerId = 1,
                            Title = "Focused impactful superstructure",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 412, DateTimeKind.Utc).AddTicks(9083)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 413, DateTimeKind.Utc).AddTicks(1259),
                            Description = "Iste quisquam unde laboriosam unde ratione. Incidunt tempore possimus aut. Aliquam laborum voluptatem asperiores magnam sit et quis fuga.",
                            OwnerId = 1,
                            Title = "Profound systematic adapter",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 413, DateTimeKind.Utc).AddTicks(1260)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 413, DateTimeKind.Utc).AddTicks(4609),
                            Description = "Voluptas sit ab praesentium maxime fugit accusantium natus quos architecto. Dolorem magni doloribus error minus eligendi doloremque quae. Assumenda ab nemo dolor rerum commodi eum. Aut blanditiis corrupti soluta vero repellendus ut. Rerum itaque distinctio ad ab sed aspernatur.",
                            OwnerId = 1,
                            Title = "Profit-focused clear-thinking archive",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 413, DateTimeKind.Utc).AddTicks(4609)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 413, DateTimeKind.Utc).AddTicks(5718),
                            Description = "Doloribus qui quo quos. Distinctio aperiam non debitis. Expedita hic reprehenderit aut ullam voluptatem numquam.",
                            OwnerId = 1,
                            Title = "Quality-focused motivating solution",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 413, DateTimeKind.Utc).AddTicks(5719)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 413, DateTimeKind.Utc).AddTicks(7984),
                            Description = "Ducimus repellat laborum aspernatur qui quae aperiam. Repellat non aliquam inventore quasi excepturi impedit nihil inventore nihil. Facilis quia ut non. Perferendis et quam est aut voluptatem ea sed. Temporibus rerum minus ut quo.",
                            OwnerId = 2,
                            Title = "Assimilated scalable product",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 413, DateTimeKind.Utc).AddTicks(7984)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 413, DateTimeKind.Utc).AddTicks(9458),
                            Description = "Blanditiis ut rerum voluptatum amet dolorem quia et aut. Voluptas mollitia sed sit voluptatem exercitationem ut est. Rerum amet nisi neque.",
                            OwnerId = 1,
                            Title = "Focused directional conglomeration",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 413, DateTimeKind.Utc).AddTicks(9458)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 414, DateTimeKind.Utc).AddTicks(3250),
                            Description = "Consequatur voluptatem iste deleniti omnis pariatur dolorum officia. Id eum et eos deleniti totam aliquam. Eos quasi molestiae quos natus ad aliquam quis nostrum. Velit ducimus minima totam corrupti omnis perferendis quam tempore et. Porro neque aut impedit rerum.",
                            OwnerId = 1,
                            Title = "Networked executive flexibility",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 414, DateTimeKind.Utc).AddTicks(3250)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 414, DateTimeKind.Utc).AddTicks(7589),
                            Description = "Necessitatibus corporis et autem nostrum ducimus quia. Amet deleniti dolorem non omnis eos ducimus nihil. Non quod non molestiae eaque illo et in. Aspernatur fuga nostrum accusantium libero. Sit atque perspiciatis quis omnis eos voluptatem ut et aperiam.",
                            OwnerId = 1,
                            Title = "Programmable 6th generation matrices",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 414, DateTimeKind.Utc).AddTicks(7589)
                        });
                });

            modelBuilder.Entity("audits_.net_react_ramine.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("DailyEmailUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("daily_email_updates");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 411, DateTimeKind.Utc).AddTicks(6713),
                            Email = "test@example.com",
                            FirstName = "User",
                            LastName = "Test",
                            Password = "password",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 411, DateTimeKind.Utc).AddTicks(6715)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 411, DateTimeKind.Utc).AddTicks(6758),
                            Email = "test2@example.com",
                            FirstName = "User",
                            LastName = "Test 2",
                            Password = "password",
                            UpdatedAt = new DateTime(2022, 10, 9, 5, 54, 24, 411, DateTimeKind.Utc).AddTicks(6758)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
