// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using audits_.net_react_ramine.Data;

#nullable disable

namespace audits_.net_react_ramine.Migrations
{
    [DbContext(typeof(AuditsDbContext))]
    [Migration("20221011154135_CreateSettingsTable")]
    partial class CreateSettingsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("audits_.net_react_ramine.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audits");

                    b.ToTable("audits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 953, DateTimeKind.Utc).AddTicks(4897),
                            Event = "invoice:send",
                            Message = "Qui consectetur tempore quia esse soluta facilis suscipit unde. Modi incidunt id ad vitae vel asperiores quae assumenda. Fuga perspiciatis vitae nobis non asperiores quis.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 953, DateTimeKind.Utc).AddTicks(4897),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 953, DateTimeKind.Utc).AddTicks(7995),
                            Event = "invoice:send",
                            Message = "Ea voluptates qui consequatur est officiis. Et dolorem at voluptatem facere aperiam. Corrupti delectus vero qui fugit nesciunt eos. Et est unde aspernatur reiciendis. Sit sunt quia praesentium et voluptas iure quibusdam consequatur. Error earum aut dolor omnis est sit itaque.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 953, DateTimeKind.Utc).AddTicks(7995),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 953, DateTimeKind.Utc).AddTicks(9613),
                            Event = "invoice:create",
                            Message = "Qui in neque ullam repellendus expedita ut repudiandae. Dolorem nihil et alias deleniti exercitationem ut non fuga harum. Hic natus voluptatibus recusandae facere a culpa qui.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 953, DateTimeKind.Utc).AddTicks(9614),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 954, DateTimeKind.Utc).AddTicks(1502),
                            Event = "authentication:new",
                            Message = "Voluptatem culpa neque recusandae blanditiis earum blanditiis commodi qui dolorum. A perspiciatis recusandae aut harum deleniti. Cumque et quaerat cupiditate. Consequatur perferendis qui quasi adipisci dicta saepe perferendis alias. Placeat quia nostrum est. Culpa quia quia rerum.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 954, DateTimeKind.Utc).AddTicks(1502),
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 954, DateTimeKind.Utc).AddTicks(2635),
                            Event = "authentication:new",
                            Message = "Optio veniam reprehenderit molestiae molestias laboriosam est fuga voluptas maxime. Error et vel est illum. Rerum et explicabo non ut illo iusto.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 954, DateTimeKind.Utc).AddTicks(2635),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 954, DateTimeKind.Utc).AddTicks(4652),
                            Event = "invoice:send",
                            Message = "Est rerum ipsam enim est. Maxime expedita nam qui est eligendi veniam. Quae enim sequi cum quia aut id explicabo qui. Eos nulla dolore nam eligendi corporis et facere. Animi expedita recusandae aut velit.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 954, DateTimeKind.Utc).AddTicks(4652),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 954, DateTimeKind.Utc).AddTicks(8705),
                            Event = "settings:change",
                            Message = "Quam aut itaque explicabo ipsum pariatur est. Dignissimos numquam adipisci ut similique et iusto eveniet et. Autem nihil ut culpa aperiam et quis aspernatur quia et. Omnis quia repellendus quod praesentium sed ducimus et. Quis qui odit sit molestiae fugit aliquam voluptatibus in. Vel cupiditate est et deserunt maiores perspiciatis cumque dolor.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 954, DateTimeKind.Utc).AddTicks(8705),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 954, DateTimeKind.Utc).AddTicks(9777),
                            Event = "authentication:new",
                            Message = "Quibusdam minima sunt sequi. Non qui tempore temporibus voluptas. Culpa beatae qui odit necessitatibus perspiciatis eius veritatis omnis modi.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 954, DateTimeKind.Utc).AddTicks(9777),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(1000),
                            Event = "authentication:logout",
                            Message = "Sint magnam ab ad est aut quaerat id fuga. Provident aperiam animi quaerat odit in placeat explicabo sit quia. Expedita et dolorem aspernatur.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(1001),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(2009),
                            Event = "authentication:logout",
                            Message = "Ipsam mollitia eveniet porro nihil omnis recusandae. Quia voluptatibus voluptas laudantium. Dolores ipsam eos voluptas. Corrupti veritatis sunt provident.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(2010),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(4231),
                            Event = "invoice:create",
                            Message = "Est velit dolorem provident. Ut ipsa dolorem ipsam recusandae et. Sequi et rem praesentium ducimus fuga minima velit voluptas ea. Quidem consequuntur libero aliquam iste voluptates quam. Non recusandae soluta corrupti itaque sed voluptatem qui consequatur. Voluptatem eius necessitatibus vel deleniti.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(4231),
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(5962),
                            Event = "authentication:new",
                            Message = "Aut consectetur et ducimus numquam quo. Pariatur in voluptatibus non impedit nisi accusantium. Quae vero recusandae quis ut sunt doloremque possimus optio consequuntur. Possimus quia impedit tempora laudantium accusamus est officiis libero id.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(5963),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(8108),
                            Event = "settings:change",
                            Message = "Voluptatem deserunt dolores omnis sequi veniam laborum qui dolorem voluptatem. Eos consequatur repellat ad. Dolores quia deleniti blanditiis consequatur et reiciendis. Explicabo laboriosam omnis porro voluptatem debitis nemo quia dignissimos. Quam facilis necessitatibus dolore minima animi nobis. Illo et et dolor repudiandae omnis.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(8108),
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(9113),
                            Event = "authentication:logout",
                            Message = "Ab nulla dolores neque. At possimus at magni minima dolore. Omnis sunt suscipit earum. Aspernatur aut rerum voluptas sed consequatur.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 955, DateTimeKind.Utc).AddTicks(9113),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 956, DateTimeKind.Utc).AddTicks(1190),
                            Event = "authentication:logout",
                            Message = "Corporis laudantium et eveniet saepe. Vero vel ex et suscipit vitae. Porro maxime sed odio quis cum et. Debitis iure sunt voluptatem est nihil omnis. Et inventore optio eligendi est reiciendis qui vel excepturi. Consectetur adipisci qui ut aut tempora.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 956, DateTimeKind.Utc).AddTicks(1190),
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 956, DateTimeKind.Utc).AddTicks(3505),
                            Event = "authentication:new",
                            Message = "Cumque placeat ipsa molestiae amet quia quod. Ipsa blanditiis corporis nostrum vitae autem exercitationem sequi voluptatem. Corrupti asperiores ut qui. Iure maiores tempora omnis libero in temporibus quod dolores. Odit nostrum quibusdam nobis mollitia consectetur officiis dolore fuga. Tenetur aut reiciendis beatae ab et similique aut.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 956, DateTimeKind.Utc).AddTicks(3505),
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 956, DateTimeKind.Utc).AddTicks(6412),
                            Event = "authentication:new",
                            Message = "Provident veritatis perferendis adipisci voluptas dolores et tenetur quidem sint. Dicta qui molestiae eos aut optio sed doloremque sint ut. Et vitae sit atque dolorem. Est est omnis veritatis voluptas autem. Libero debitis nulla ut rerum velit est assumenda voluptas. Tenetur aut provident modi nisi et vitae quia.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 956, DateTimeKind.Utc).AddTicks(6412),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 956, DateTimeKind.Utc).AddTicks(7689),
                            Event = "settings:change",
                            Message = "Velit voluptatem ratione dicta ea eius voluptatem. Voluptatem nihil unde aperiam quas aut. Et libero aut laudantium incidunt explicabo molestiae ut.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 956, DateTimeKind.Utc).AddTicks(7690),
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 957, DateTimeKind.Utc).AddTicks(1166),
                            Event = "authentication:logout",
                            Message = "Aperiam veniam voluptatem quod minus unde odio temporibus. Nemo qui commodi sit est rerum sint voluptatem. Pariatur quae autem vitae. Ipsum dolore unde magnam vero. Quo maxime non tempora molestias qui. Non cum assumenda culpa.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 957, DateTimeKind.Utc).AddTicks(1166),
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 957, DateTimeKind.Utc).AddTicks(4096),
                            Event = "authentication:new",
                            Message = "Odit adipisci non autem autem labore ipsa sed et. Autem maxime id quia et et. Cumque cum ea distinctio. Enim culpa cum consequatur omnis sequi aut sed nam perferendis.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 957, DateTimeKind.Utc).AddTicks(4096),
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 957, DateTimeKind.Utc).AddTicks(6832),
                            Event = "invoice:send",
                            Message = "Consequatur reprehenderit qui iusto iste provident vel minima. Pariatur inventore soluta alias doloribus atque quisquam. Necessitatibus possimus enim eveniet consequatur omnis. Ut dolores eum error voluptate soluta voluptatibus deleniti. Repellendus ipsa harum enim expedita odit aspernatur similique corrupti odio.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 957, DateTimeKind.Utc).AddTicks(6833),
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 957, DateTimeKind.Utc).AddTicks(7979),
                            Event = "authentication:logout",
                            Message = "Expedita ut quis quibusdam et. Sit non aut doloribus tempore cupiditate voluptas aut at quam. Debitis nam beatae amet eveniet cupiditate laboriosam.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 957, DateTimeKind.Utc).AddTicks(7979),
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 957, DateTimeKind.Utc).AddTicks(9748),
                            Event = "settings:change",
                            Message = "Debitis nisi provident et pariatur cupiditate rem ad. Dolorem cupiditate ab molestiae impedit. Atque iusto deserunt hic occaecati. Quaerat aut enim molestiae totam velit. Nobis soluta consequatur impedit quia saepe. Impedit quis odio maiores.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 957, DateTimeKind.Utc).AddTicks(9749),
                            UserId = 2
                        },
                        new
                        {
                            Id = 24,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(1695),
                            Event = "invoice:create",
                            Message = "Similique id deserunt et est repellendus illum tenetur non rerum. Sequi sit cupiditate recusandae aut ea ut blanditiis debitis doloremque. Ullam consequatur officia a consequuntur quia. Qui ut facilis vitae est maiores nobis dolore aut. Unde qui voluptatem ipsum.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(1695),
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(3092),
                            Event = "authentication:logout",
                            Message = "Animi non molestiae consequatur id. Enim dolorum adipisci magni ut temporibus eum. Eos saepe consequatur temporibus possimus. Repellendus at eaque voluptatum. Facilis maiores expedita quia eos enim.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(3092),
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(4552),
                            Event = "authentication:logout",
                            Message = "Ipsam est architecto consequuntur. Odit qui eum et est id voluptas sint. Nulla eaque enim iusto voluptatem amet eos et. Ea quae non qui repellat eos ab et quidem sunt.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(4552),
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(5945),
                            Event = "invoice:create",
                            Message = "Quam ut qui eos molestiae facilis. Dolores qui exercitationem neque maiores iusto. Voluptatem quam et est est illo.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(5946),
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(8138),
                            Event = "invoice:create",
                            Message = "In maxime et consequatur ab quisquam est. Excepturi at eos officia occaecati voluptatibus deleniti dolore non deleniti. Nulla quam temporibus et laudantium quos delectus maxime facere. Suscipit et cum sunt necessitatibus pariatur omnis accusamus. Velit laboriosam itaque cupiditate dolorem. Aliquam tempora veniam doloremque.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(8138),
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(9690),
                            Event = "authentication:logout",
                            Message = "Vel ad omnis et temporibus voluptatem consequatur. Aliquam excepturi molestias odit nisi est eius itaque animi corrupti. Alias laborum maxime laudantium illum saepe. Temporibus quae ex enim quod esse earum doloribus.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 958, DateTimeKind.Utc).AddTicks(9690),
                            UserId = 1
                        },
                        new
                        {
                            Id = 30,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 959, DateTimeKind.Utc).AddTicks(1572),
                            Event = "invoice:send",
                            Message = "Exercitationem repudiandae ad ex doloremque. Sed nam eius et reiciendis delectus. Ea dicta ab quae non error placeat quae molestiae culpa. Voluptate ipsam accusamus dolorem. Nihil ipsam autem quidem delectus et. Minima earum perferendis ut dolore excepturi.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 959, DateTimeKind.Utc).AddTicks(1572),
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 959, DateTimeKind.Utc).AddTicks(2892),
                            Event = "invoice:send",
                            Message = "Dolorem ipsam nobis perferendis est molestiae nihil neque. Et facere aut itaque voluptatibus. Commodi minima dolore enim ea dolor nisi quod.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 959, DateTimeKind.Utc).AddTicks(2892),
                            UserId = 1
                        },
                        new
                        {
                            Id = 32,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 959, DateTimeKind.Utc).AddTicks(6954),
                            Event = "authentication:new",
                            Message = "Autem molestias dolores et enim itaque. Exercitationem ea est officiis quasi voluptas. Officiis dolorem qui cumque quam modi maiores eum sed ratione. Id quaerat ipsam et officiis labore fugiat eos aut amet. Unde ipsa et illum inventore quaerat hic exercitationem.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 959, DateTimeKind.Utc).AddTicks(6954),
                            UserId = 1
                        },
                        new
                        {
                            Id = 33,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 959, DateTimeKind.Utc).AddTicks(9161),
                            Event = "invoice:create",
                            Message = "Odit alias voluptatem nemo incidunt suscipit nulla minus. Quas vitae sequi vel et iure recusandae aut. Fuga qui provident nihil voluptatum qui ut.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 959, DateTimeKind.Utc).AddTicks(9161),
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 960, DateTimeKind.Utc).AddTicks(1067),
                            Event = "authentication:logout",
                            Message = "Veniam aut aut quia voluptatum voluptates doloremque atque ipsum. Voluptas consequatur ipsam tempore qui. Et ea minus qui voluptatem possimus vero eligendi at id.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 960, DateTimeKind.Utc).AddTicks(1068),
                            UserId = 1
                        },
                        new
                        {
                            Id = 35,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 960, DateTimeKind.Utc).AddTicks(2695),
                            Event = "authentication:logout",
                            Message = "Et excepturi esse qui ut omnis et. Quia ratione porro in quis et molestiae est nulla. Amet eum doloribus repudiandae est repudiandae. Minus est qui quos vel beatae deserunt et culpa et.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 960, DateTimeKind.Utc).AddTicks(2695),
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 960, DateTimeKind.Utc).AddTicks(4665),
                            Event = "invoice:create",
                            Message = "Cupiditate velit minus voluptas officiis sit consequuntur velit consequatur. Fugit itaque molestiae consequatur quo est molestiae. Dolor doloribus modi nobis magnam cupiditate ipsam rem quibusdam. Accusantium dolores quae dolorum. Et consequuntur animi sapiente ut et cumque molestiae nostrum.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 960, DateTimeKind.Utc).AddTicks(4666),
                            UserId = 1
                        },
                        new
                        {
                            Id = 37,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 960, DateTimeKind.Utc).AddTicks(6161),
                            Event = "authentication:new",
                            Message = "Et ad magnam aliquid aut quos nihil amet excepturi. Fugiat cum ad quod quidem praesentium ut sed. Quae repudiandae et non fuga et est. Praesentium ut similique architecto ea.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 960, DateTimeKind.Utc).AddTicks(6161),
                            UserId = 1
                        },
                        new
                        {
                            Id = 38,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 960, DateTimeKind.Utc).AddTicks(7338),
                            Event = "settings:change",
                            Message = "Reiciendis vitae hic et maiores qui quis libero enim. Necessitatibus libero doloremque dolor laudantium temporibus. Molestiae sapiente dolore repudiandae ipsum dicta illo placeat.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 960, DateTimeKind.Utc).AddTicks(7338),
                            UserId = 2
                        },
                        new
                        {
                            Id = 39,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 961, DateTimeKind.Utc).AddTicks(2217),
                            Event = "authentication:logout",
                            Message = "Velit optio reiciendis vel id molestiae ut vel hic sed. Sapiente maxime et illum id animi. Est qui consectetur eius cupiditate blanditiis nisi delectus tenetur cupiditate. Vitae quasi consequatur harum eaque accusamus culpa. Quo ex labore sequi distinctio laborum aperiam aut delectus. Vitae laudantium sed accusantium fugit ipsum rerum porro debitis.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 961, DateTimeKind.Utc).AddTicks(2218),
                            UserId = 2
                        },
                        new
                        {
                            Id = 40,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 961, DateTimeKind.Utc).AddTicks(4663),
                            Event = "invoice:create",
                            Message = "Consequatur consectetur est et ut est eos autem eveniet. Unde vero perferendis autem quidem ut accusantium. Ut rem voluptas in et perferendis qui voluptatem itaque.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 961, DateTimeKind.Utc).AddTicks(4663),
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 961, DateTimeKind.Utc).AddTicks(6425),
                            Event = "authentication:new",
                            Message = "Veniam eaque aperiam facilis earum ut adipisci magni. Laborum qui quaerat aut sapiente impedit quas. Dolor temporibus sapiente repellendus sed iusto consequuntur sapiente assumenda.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 961, DateTimeKind.Utc).AddTicks(6426),
                            UserId = 1
                        },
                        new
                        {
                            Id = 42,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 961, DateTimeKind.Utc).AddTicks(8217),
                            Event = "invoice:create",
                            Message = "Excepturi dolorem omnis ut et nostrum hic magni est. Vel eius occaecati placeat quis aliquid commodi et nisi. Aliquid veniam est nihil sunt aliquam. Quae placeat magni sit quod deserunt sit vero. Culpa dolorum reiciendis eaque.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 961, DateTimeKind.Utc).AddTicks(8217),
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 961, DateTimeKind.Utc).AddTicks(9407),
                            Event = "invoice:send",
                            Message = "Recusandae ab optio corporis repudiandae doloremque et quibusdam corporis laudantium. Earum aspernatur atque nemo eum. Et culpa tempore et in nemo culpa ipsam eos.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 961, DateTimeKind.Utc).AddTicks(9407),
                            UserId = 1
                        },
                        new
                        {
                            Id = 44,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 962, DateTimeKind.Utc).AddTicks(974),
                            Event = "invoice:create",
                            Message = "Dolorum deserunt sint pariatur. Eligendi voluptatem sint qui voluptas non ducimus quod est ut. Quo aliquam consequatur laudantium molestiae mollitia. Distinctio nihil neque aut qui nihil. Esse voluptas est dolore laboriosam.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 962, DateTimeKind.Utc).AddTicks(975),
                            UserId = 1
                        },
                        new
                        {
                            Id = 45,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 962, DateTimeKind.Utc).AddTicks(5113),
                            Event = "authentication:new",
                            Message = "Sed magni error vel velit totam repellat corrupti est eius. Consequatur exercitationem dolorem a est expedita ipsum. Eos dolorem quo excepturi. Atque temporibus aliquid quo omnis at perferendis voluptas aut. Et consequatur et illum reprehenderit nam quas dicta. Vel est quis et ipsa voluptatem necessitatibus porro.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 962, DateTimeKind.Utc).AddTicks(5113),
                            UserId = 2
                        },
                        new
                        {
                            Id = 46,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 962, DateTimeKind.Utc).AddTicks(8315),
                            Event = "settings:change",
                            Message = "Sunt velit unde minus magni. Autem tempore minima ut sint. Optio possimus enim deserunt ratione esse qui vel.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 962, DateTimeKind.Utc).AddTicks(8317),
                            UserId = 2
                        },
                        new
                        {
                            Id = 47,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 963, DateTimeKind.Utc).AddTicks(857),
                            Event = "authentication:logout",
                            Message = "Mollitia reprehenderit occaecati maxime aut. Veritatis maxime culpa rerum soluta corrupti aut at ut. Ex nemo mollitia quo nobis asperiores. Iusto quae ut placeat impedit.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 963, DateTimeKind.Utc).AddTicks(858),
                            UserId = 2
                        },
                        new
                        {
                            Id = 48,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 977, DateTimeKind.Utc).AddTicks(3204),
                            Event = "invoice:create",
                            Message = "Unde maiores in eius. Laborum sit officiis expedita voluptatem assumenda. Facere neque repellendus aperiam ut aut cumque aperiam vel blanditiis. Voluptas eaque facere vitae odio consequatur sit. Quod tempora eum est et aut totam illo ipsa velit.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 977, DateTimeKind.Utc).AddTicks(3208),
                            UserId = 1
                        },
                        new
                        {
                            Id = 49,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 977, DateTimeKind.Utc).AddTicks(6585),
                            Event = "settings:change",
                            Message = "Qui possimus repellat mollitia molestias et enim laudantium consequatur sed. Voluptatem sit provident laborum et animi unde quam veniam. Nemo incidunt ea consequuntur consectetur earum et dolores. Nobis omnis ut iure error sit soluta aut sunt. Corrupti occaecati dolore consequuntur aut aut rerum ut. Explicabo quidem dolores sed.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 977, DateTimeKind.Utc).AddTicks(6586),
                            UserId = 1
                        },
                        new
                        {
                            Id = 50,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 977, DateTimeKind.Utc).AddTicks(8250),
                            Event = "settings:change",
                            Message = "Consequatur fuga tempore velit veniam deleniti consequatur. Corrupti error sit sunt voluptatem occaecati sint non porro at. Rem nisi perferendis recusandae ut sit ut sit. Consequuntur eius eum earum aut a.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 977, DateTimeKind.Utc).AddTicks(8250),
                            UserId = 2
                        },
                        new
                        {
                            Id = 51,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 977, DateTimeKind.Utc).AddTicks(9757),
                            Event = "authentication:logout",
                            Message = "Corrupti vitae cumque molestiae. Et ut est omnis libero facere. Doloremque aspernatur velit excepturi nihil voluptatum voluptatem sit iure. Quis quibusdam eum est corrupti dolores voluptas earum sapiente.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 977, DateTimeKind.Utc).AddTicks(9757),
                            UserId = 1
                        },
                        new
                        {
                            Id = 52,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(2309),
                            Event = "invoice:send",
                            Message = "Soluta aut praesentium qui iste consequatur fugit atque. Nostrum dicta quisquam qui et quis est vero expedita commodi. Quia cupiditate labore dolorem dignissimos repellat temporibus id voluptas et. Et non assumenda iste consequatur. Odit amet dolorem a veritatis assumenda quod. Sint repudiandae assumenda voluptatem nihil rerum.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(2309),
                            UserId = 2
                        },
                        new
                        {
                            Id = 53,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(4123),
                            Event = "authentication:logout",
                            Message = "Ipsum et omnis doloremque quod eligendi quo. Ullam quaerat ipsam iure aliquid velit. Ratione et unde accusantium dicta cumque quo ratione qui laudantium. Recusandae voluptatum veniam et non. Alias eveniet repellat ut asperiores.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(4124),
                            UserId = 1
                        },
                        new
                        {
                            Id = 54,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(5081),
                            Event = "invoice:send",
                            Message = "Voluptatum expedita excepturi quos in architecto ab nostrum et. A sit nulla quia. Est est quae ipsa.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(5081),
                            UserId = 2
                        },
                        new
                        {
                            Id = 55,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(6550),
                            Event = "invoice:create",
                            Message = "Magnam iure recusandae sunt adipisci atque illo. Architecto incidunt totam ut quis tempore sequi molestiae. Velit non sapiente cum. Cupiditate eos et quo dolores sed inventore illum.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(6550),
                            UserId = 1
                        },
                        new
                        {
                            Id = 56,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(8124),
                            Event = "invoice:create",
                            Message = "Aspernatur facere excepturi aut in. Velit odit voluptas in vel dolor porro qui iure. Perspiciatis architecto quis animi asperiores qui accusantium itaque porro. Officiis quia et quia eaque.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(8124),
                            UserId = 2
                        },
                        new
                        {
                            Id = 57,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(9267),
                            Event = "invoice:create",
                            Message = "Sapiente cupiditate blanditiis et. Eum autem eaque natus adipisci fugit qui saepe veritatis. Excepturi id occaecati in est ducimus voluptas qui.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 978, DateTimeKind.Utc).AddTicks(9268),
                            UserId = 1
                        },
                        new
                        {
                            Id = 58,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 979, DateTimeKind.Utc).AddTicks(1623),
                            Event = "invoice:send",
                            Message = "Vel sapiente cum et modi laboriosam nobis. Odio aut et enim corrupti molestiae dolorum excepturi. Consequuntur officia maxime reprehenderit iure quaerat cumque esse quo facere. Dignissimos ad sint pariatur temporibus dolorum quibusdam qui. Doloremque doloribus alias saepe esse. Error eos reiciendis quia quasi labore.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 979, DateTimeKind.Utc).AddTicks(1623),
                            UserId = 1
                        },
                        new
                        {
                            Id = 59,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 979, DateTimeKind.Utc).AddTicks(3738),
                            Event = "settings:change",
                            Message = "Sit consequatur aliquam quia quis voluptatem aut. Atque aspernatur porro illum et voluptatem quasi et veritatis ea. Consequatur dolore dolor dolorum. Eum asperiores inventore quae architecto quas. Necessitatibus voluptatem enim saepe ratione. Voluptatibus rem facere aut ut modi perferendis velit.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 979, DateTimeKind.Utc).AddTicks(3738),
                            UserId = 1
                        },
                        new
                        {
                            Id = 60,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 979, DateTimeKind.Utc).AddTicks(4989),
                            Event = "authentication:new",
                            Message = "Facilis dicta tenetur et quas minus vitae. Id dignissimos veritatis beatae et corporis voluptatem consectetur et tempore. Repellendus assumenda dolores debitis accusantium.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 979, DateTimeKind.Utc).AddTicks(4989),
                            UserId = 1
                        },
                        new
                        {
                            Id = 61,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 979, DateTimeKind.Utc).AddTicks(7035),
                            Event = "settings:change",
                            Message = "Voluptatem eum vel nobis quisquam repellat magnam libero. Consectetur provident error accusamus ut sed cupiditate eius saepe et. Maiores temporibus et distinctio. Blanditiis aliquam sed nostrum distinctio enim explicabo aut. Voluptatem sit dolorum corporis aut velit nostrum.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 979, DateTimeKind.Utc).AddTicks(7036),
                            UserId = 1
                        },
                        new
                        {
                            Id = 62,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 979, DateTimeKind.Utc).AddTicks(8194),
                            Event = "invoice:create",
                            Message = "Beatae velit repellat in hic officiis rerum ipsum praesentium. Mollitia numquam voluptate id aspernatur pariatur ipsum voluptatem est. Quia eius nobis repellat.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 979, DateTimeKind.Utc).AddTicks(8195),
                            UserId = 2
                        },
                        new
                        {
                            Id = 63,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(801),
                            Event = "invoice:send",
                            Message = "Asperiores doloremque sit voluptas ea repellat eos id. Autem voluptates cum est in voluptatem odio vitae nisi. Ut dolore animi harum sint harum expedita soluta dolor est. Maiores dicta et sequi ut accusamus dolores illo. Esse non accusantium qui tenetur. Rerum sint modi qui iure autem porro consectetur.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(802),
                            UserId = 2
                        },
                        new
                        {
                            Id = 64,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(2124),
                            Event = "invoice:send",
                            Message = "Iusto dolorem eos sed aliquid id est sunt. Rerum exercitationem quod commodi voluptatem quis consequatur vel. Quae et voluptatem atque rerum sunt minus dolorem debitis.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(2124),
                            UserId = 1
                        },
                        new
                        {
                            Id = 65,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(3929),
                            Event = "authentication:new",
                            Message = "Velit dicta id quos dolor laudantium deserunt. Et recusandae consequuntur rerum et voluptatum cum autem. Perferendis et sit architecto aspernatur omnis. Omnis ipsam sit temporibus dolor. Consequuntur facere voluptate modi ut.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(3929),
                            UserId = 1
                        },
                        new
                        {
                            Id = 66,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(5997),
                            Event = "settings:change",
                            Message = "Iste ut qui quos velit. Dolorum sunt soluta provident labore iure voluptatum ut nam. Voluptatem maiores ipsa nihil. Nihil ipsam placeat facere minus et similique sunt voluptas ut. Sed eum tempore ut laborum a ut hic atque velit.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(5998),
                            UserId = 1
                        },
                        new
                        {
                            Id = 67,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(7568),
                            Event = "authentication:logout",
                            Message = "Perferendis aut ipsa aliquid aut in sunt minus nemo. Iste sit rem dicta nemo quae a. Et ut illo cupiditate. Adipisci ullam sint dolorem vel rerum quia placeat nesciunt.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(7568),
                            UserId = 1
                        },
                        new
                        {
                            Id = 68,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(9817),
                            Event = "invoice:create",
                            Message = "Est eligendi velit officia molestiae placeat nihil eaque et deleniti. Consequatur optio quibusdam illo aut aperiam aut ut. Non velit voluptatibus fugit quae perspiciatis animi praesentium explicabo rerum. Doloribus quasi dolorem molestiae vitae. Tempore temporibus autem vero aspernatur. Sed ea animi libero amet.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 980, DateTimeKind.Utc).AddTicks(9817),
                            UserId = 1
                        },
                        new
                        {
                            Id = 69,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 981, DateTimeKind.Utc).AddTicks(1341),
                            Event = "settings:change",
                            Message = "Laudantium alias quos laudantium omnis consequatur sed expedita et ut. Et ut impedit quia voluptas doloribus. Ut distinctio velit expedita nulla non eos nobis sed.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 981, DateTimeKind.Utc).AddTicks(1342),
                            UserId = 1
                        },
                        new
                        {
                            Id = 70,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 981, DateTimeKind.Utc).AddTicks(2588),
                            Event = "authentication:logout",
                            Message = "Vitae et laudantium aut dolorem cupiditate cumque qui reprehenderit adipisci. Ipsa laborum quia cumque. Aut aliquid accusantium culpa placeat error numquam error.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 981, DateTimeKind.Utc).AddTicks(2589),
                            UserId = 2
                        },
                        new
                        {
                            Id = 71,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 981, DateTimeKind.Utc).AddTicks(5018),
                            Event = "invoice:send",
                            Message = "Maxime non debitis est dolor quis laboriosam quis fuga et. Consectetur consectetur molestias repellendus officia incidunt qui ut aut. Sit veniam nulla sunt temporibus. Officiis quia maxime vel ad blanditiis laboriosam dolore nemo autem. Architecto porro aperiam quisquam repudiandae omnis. Excepturi et voluptatem omnis error.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 981, DateTimeKind.Utc).AddTicks(5018),
                            UserId = 2
                        },
                        new
                        {
                            Id = 72,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 981, DateTimeKind.Utc).AddTicks(6146),
                            Event = "settings:change",
                            Message = "Excepturi exercitationem dolore commodi molestiae consequatur hic ducimus laboriosam qui. Ut dolorem ipsam quod repudiandae. Est accusantium dolores velit est eos.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 981, DateTimeKind.Utc).AddTicks(6146),
                            UserId = 2
                        },
                        new
                        {
                            Id = 73,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 981, DateTimeKind.Utc).AddTicks(7982),
                            Event = "invoice:create",
                            Message = "Id voluptates placeat sint quidem consequatur omnis eum. Odio consequatur rerum necessitatibus amet. Occaecati incidunt labore repudiandae ea aperiam voluptas eum aut deserunt. Vel dicta ut asperiores iusto et quidem suscipit voluptas quia.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 981, DateTimeKind.Utc).AddTicks(7983),
                            UserId = 2
                        },
                        new
                        {
                            Id = 74,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 982, DateTimeKind.Utc).AddTicks(319),
                            Event = "authentication:new",
                            Message = "Eveniet inventore sit rem. Voluptas nisi mollitia ullam ab veritatis. Velit fugiat neque praesentium omnis quia omnis. Veniam asperiores voluptas nesciunt velit exercitationem dicta commodi. Officia animi fugiat quo sunt ad maxime quas aperiam. Quas ut officia magnam delectus officiis.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 982, DateTimeKind.Utc).AddTicks(319),
                            UserId = 2
                        },
                        new
                        {
                            Id = 75,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 982, DateTimeKind.Utc).AddTicks(1283),
                            Event = "authentication:logout",
                            Message = "Quaerat consequatur sint corrupti. Aut sint repellat consequatur. Temporibus corporis rerum quod modi.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 982, DateTimeKind.Utc).AddTicks(1284),
                            UserId = 2
                        },
                        new
                        {
                            Id = 76,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 982, DateTimeKind.Utc).AddTicks(2252),
                            Event = "invoice:create",
                            Message = "Consequuntur ipsa aspernatur corporis corporis. Nobis fugiat dolorem et odit doloremque. Reiciendis quis aliquam et doloremque.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 982, DateTimeKind.Utc).AddTicks(2253),
                            UserId = 2
                        },
                        new
                        {
                            Id = 77,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 982, DateTimeKind.Utc).AddTicks(4021),
                            Event = "authentication:logout",
                            Message = "Aut consequuntur omnis molestiae vitae quaerat explicabo et. Pariatur facere in labore dignissimos fuga eligendi. Nostrum animi rerum at sapiente magni adipisci atque nostrum. Ut sed non amet ipsum ad consequatur.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 982, DateTimeKind.Utc).AddTicks(4023),
                            UserId = 1
                        },
                        new
                        {
                            Id = 78,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 982, DateTimeKind.Utc).AddTicks(5287),
                            Event = "authentication:logout",
                            Message = "Necessitatibus et rem autem. Quia accusantium omnis qui tenetur autem assumenda. Dicta occaecati magnam consequatur aut sit laborum consequatur in.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 982, DateTimeKind.Utc).AddTicks(5287),
                            UserId = 1
                        },
                        new
                        {
                            Id = 79,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 983, DateTimeKind.Utc).AddTicks(1927),
                            Event = "authentication:logout",
                            Message = "Cupiditate blanditiis ut distinctio aut esse deleniti. Ab dolores perspiciatis autem ipsam quidem quaerat libero maxime. Ut in officia sed ut quos. Sunt consequatur vel porro est labore est exercitationem. Dolorem aliquam ab ea impedit. Cumque et voluptatem omnis veritatis et et expedita voluptas odit.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 983, DateTimeKind.Utc).AddTicks(1929),
                            UserId = 1
                        },
                        new
                        {
                            Id = 80,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 983, DateTimeKind.Utc).AddTicks(6148),
                            Event = "authentication:new",
                            Message = "Et voluptatibus harum dolor voluptates. Est voluptas adipisci voluptatem quia excepturi non harum minima. Officia fuga est eos repudiandae nisi officia expedita quo exercitationem. Soluta nihil non nihil enim quia totam. Id animi ipsam eum possimus quibusdam molestias.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 983, DateTimeKind.Utc).AddTicks(6150),
                            UserId = 1
                        },
                        new
                        {
                            Id = 81,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 983, DateTimeKind.Utc).AddTicks(9486),
                            Event = "authentication:logout",
                            Message = "Sint ad cumque et ullam repudiandae. Sed assumenda ut illo ex autem corporis sint aut occaecati. Neque excepturi nemo aut eos. Sequi quia dolores ex mollitia. Tenetur neque ab inventore.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 983, DateTimeKind.Utc).AddTicks(9488),
                            UserId = 1
                        },
                        new
                        {
                            Id = 82,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 984, DateTimeKind.Utc).AddTicks(719),
                            Event = "invoice:send",
                            Message = "Et natus iusto odit voluptates. Totam aut voluptatem voluptatem impedit id. Aut qui dolorum laboriosam voluptas fuga beatae. Voluptatum nesciunt maiores deleniti sit.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 984, DateTimeKind.Utc).AddTicks(719),
                            UserId = 1
                        },
                        new
                        {
                            Id = 83,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 984, DateTimeKind.Utc).AddTicks(2782),
                            Event = "authentication:new",
                            Message = "Quisquam sunt reprehenderit quia omnis aut error magni unde. Consectetur vel quo aut a labore expedita reiciendis consequatur. Odit doloremque debitis tenetur. Ipsa vitae illo itaque ut odio ea voluptatibus totam praesentium.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 984, DateTimeKind.Utc).AddTicks(2783),
                            UserId = 2
                        },
                        new
                        {
                            Id = 84,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 984, DateTimeKind.Utc).AddTicks(5109),
                            Event = "invoice:create",
                            Message = "Debitis labore velit sed aut dolor unde officiis explicabo. Est aliquam aliquid placeat accusamus. Vel veniam ducimus eligendi similique occaecati.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 984, DateTimeKind.Utc).AddTicks(5110),
                            UserId = 2
                        },
                        new
                        {
                            Id = 85,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 984, DateTimeKind.Utc).AddTicks(9151),
                            Event = "invoice:create",
                            Message = "Sit aut et labore voluptates voluptatem veniam molestiae vitae. Aut quos deleniti animi in earum debitis eveniet voluptatem saepe. Laboriosam qui consequatur provident aut provident minima quae soluta. Quis et omnis magni architecto vitae quam.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 984, DateTimeKind.Utc).AddTicks(9152),
                            UserId = 2
                        },
                        new
                        {
                            Id = 86,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 985, DateTimeKind.Utc).AddTicks(1628),
                            Event = "invoice:send",
                            Message = "Facere occaecati officiis ut ab voluptas officia. Ut ratione quod dolor autem. Libero facilis consequuntur ipsam cupiditate rerum itaque sapiente et modi.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 985, DateTimeKind.Utc).AddTicks(1629),
                            UserId = 2
                        },
                        new
                        {
                            Id = 87,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 985, DateTimeKind.Utc).AddTicks(3590),
                            Event = "invoice:create",
                            Message = "Est rerum ut molestiae. Magnam asperiores libero rerum delectus voluptate ea quidem vero repudiandae. Unde velit sunt et quis pariatur. Porro modi atque non voluptatum.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 985, DateTimeKind.Utc).AddTicks(3591),
                            UserId = 1
                        },
                        new
                        {
                            Id = 88,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 987, DateTimeKind.Utc).AddTicks(3740),
                            Event = "authentication:new",
                            Message = "Nobis similique ut consectetur hic impedit. Quod quo dolorem molestiae et velit ipsa vel aut amet. Est et ex accusamus recusandae rem dolorem.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 987, DateTimeKind.Utc).AddTicks(3743),
                            UserId = 2
                        },
                        new
                        {
                            Id = 89,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 987, DateTimeKind.Utc).AddTicks(4919),
                            Event = "invoice:create",
                            Message = "Dolorum aut amet dolores quod. Ut laborum quae nostrum. Est officia voluptatem cum vitae nulla. Numquam culpa enim qui.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 987, DateTimeKind.Utc).AddTicks(4919),
                            UserId = 1
                        },
                        new
                        {
                            Id = 90,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 987, DateTimeKind.Utc).AddTicks(6148),
                            Event = "authentication:new",
                            Message = "Ut non dolor excepturi. Ea et et qui ipsam unde veniam fugiat. Dolorem quia porro totam fuga. Tempora soluta sed praesentium eos error.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 987, DateTimeKind.Utc).AddTicks(6149),
                            UserId = 2
                        },
                        new
                        {
                            Id = 91,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 987, DateTimeKind.Utc).AddTicks(7899),
                            Event = "authentication:new",
                            Message = "Et inventore ullam officiis soluta ut eum. Incidunt voluptas numquam et ipsa fugiat. Adipisci ea quia aut. Illum magnam quidem ex quisquam officiis ad et natus eos.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 987, DateTimeKind.Utc).AddTicks(7900),
                            UserId = 1
                        },
                        new
                        {
                            Id = 92,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 988, DateTimeKind.Utc).AddTicks(1157),
                            Event = "authentication:logout",
                            Message = "Excepturi in doloremque eius atque necessitatibus velit earum labore. Ipsa et et et quia ut quia. Impedit impedit cum officiis excepturi mollitia voluptatem placeat mollitia rerum. Eveniet facere pariatur quia quo a. Qui praesentium assumenda ea architecto omnis autem est et tempora.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 988, DateTimeKind.Utc).AddTicks(1157),
                            UserId = 2
                        },
                        new
                        {
                            Id = 93,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 988, DateTimeKind.Utc).AddTicks(2293),
                            Event = "invoice:create",
                            Message = "Voluptatem rerum suscipit omnis et rem perspiciatis eligendi eum. Temporibus maxime ut dolore voluptate dolor reprehenderit. Consequatur itaque quod est.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 988, DateTimeKind.Utc).AddTicks(2293),
                            UserId = 1
                        },
                        new
                        {
                            Id = 94,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 988, DateTimeKind.Utc).AddTicks(4544),
                            Event = "authentication:logout",
                            Message = "Quaerat omnis esse nihil ut. Magni provident atque maiores reiciendis. Inventore mollitia libero molestiae voluptas. Magni incidunt qui iure sunt dolores. Aut rerum asperiores natus debitis ea.",
                            Status = "error",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 988, DateTimeKind.Utc).AddTicks(4546),
                            UserId = 2
                        },
                        new
                        {
                            Id = 95,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 989, DateTimeKind.Utc).AddTicks(4608),
                            Event = "invoice:create",
                            Message = "Officia aliquam qui tempora animi at. Eos quasi libero temporibus veniam. Accusamus praesentium harum aliquam laboriosam. Quod qui qui ipsa quia.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 989, DateTimeKind.Utc).AddTicks(4612),
                            UserId = 1
                        },
                        new
                        {
                            Id = 96,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 989, DateTimeKind.Utc).AddTicks(9217),
                            Event = "authentication:logout",
                            Message = "Hic nam sunt perspiciatis nesciunt quis ut deserunt hic dolorem. Non blanditiis harum quis ea autem eum. Eius fuga adipisci ullam et nam explicabo.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 989, DateTimeKind.Utc).AddTicks(9219),
                            UserId = 2
                        },
                        new
                        {
                            Id = 97,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 990, DateTimeKind.Utc).AddTicks(1359),
                            Event = "authentication:new",
                            Message = "Omnis recusandae nulla dicta nihil molestiae consequatur soluta omnis. Omnis consequatur velit ducimus voluptatum iste fugiat. Veniam inventore dicta natus sit sint ea nihil sint. Fugit voluptas et expedita recusandae hic. Tenetur aliquam deserunt necessitatibus.",
                            Status = "started",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 990, DateTimeKind.Utc).AddTicks(1370),
                            UserId = 1
                        },
                        new
                        {
                            Id = 98,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 990, DateTimeKind.Utc).AddTicks(4840),
                            Event = "authentication:new",
                            Message = "Optio quibusdam minus rerum necessitatibus dolore enim excepturi adipisci. Tempore voluptatem non et. Numquam aut consectetur sed aut impedit est rerum. Voluptatem aut eum ut. Nam doloremque aut praesentium.",
                            Status = "finished",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 990, DateTimeKind.Utc).AddTicks(4842),
                            UserId = 1
                        },
                        new
                        {
                            Id = 99,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 992, DateTimeKind.Utc).AddTicks(4140),
                            Event = "invoice:send",
                            Message = "Sit nostrum sequi consequuntur voluptatibus quis. Perspiciatis reprehenderit quo nesciunt quos esse accusamus suscipit. Natus illum voluptas explicabo sit ex.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 992, DateTimeKind.Utc).AddTicks(4143),
                            UserId = 1
                        },
                        new
                        {
                            Id = 100,
                            Context = "{}",
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 992, DateTimeKind.Utc).AddTicks(6267),
                            Event = "invoice:send",
                            Message = "Id ex nulla ex nulla fugit in. Qui maxime est aut explicabo mollitia alias odio. Dolores voluptas corporis et.",
                            Status = "in progress",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 992, DateTimeKind.Utc).AddTicks(6267),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("audits_.net_react_ramine.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 951, DateTimeKind.Utc).AddTicks(1953),
                            Description = "Voluptatibus eaque aut impedit aut voluptatibus quas sapiente mollitia illum. Totam maiores illo doloribus. Laborum cupiditate similique ut unde non. Ut et dolore voluptas qui ab et. Laboriosam fuga ut at eaque et. Esse dolorum est non amet quam omnis deleniti facilis.",
                            OwnerId = 2,
                            Title = "Switchable attitude-oriented neural-net",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 951, DateTimeKind.Utc).AddTicks(1954)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 951, DateTimeKind.Utc).AddTicks(4009),
                            Description = "Ullam nisi a maxime maxime ea non doloribus. Odit saepe perferendis qui sit incidunt rerum harum cumque sapiente. Quisquam ratione debitis aliquam similique ut itaque nobis.",
                            OwnerId = 1,
                            Title = "Balanced system-worthy frame",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 951, DateTimeKind.Utc).AddTicks(4010)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 951, DateTimeKind.Utc).AddTicks(6185),
                            Description = "Rerum et earum beatae totam aut natus cum quam. Alias et ut fugit dolor soluta voluptas ipsa atque distinctio. Dolores doloremque nesciunt expedita ad.",
                            OwnerId = 1,
                            Title = "Re-contextualized scalable paradigm",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 951, DateTimeKind.Utc).AddTicks(6187)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 951, DateTimeKind.Utc).AddTicks(7767),
                            Description = "Aliquam et unde rerum tenetur. Quod dolor iure suscipit repudiandae facere et. Rerum nobis cumque quo. Saepe qui nihil iure illo quas ex vero dolor.",
                            OwnerId = 1,
                            Title = "User-friendly dedicated methodology",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 951, DateTimeKind.Utc).AddTicks(7767)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 951, DateTimeKind.Utc).AddTicks(9431),
                            Description = "Odio architecto exercitationem eum corrupti. Autem consectetur et provident ut incidunt reprehenderit. Ut et aut harum ipsum sit molestias alias ad. Cupiditate et aliquid laborum a consequuntur delectus ducimus.",
                            OwnerId = 2,
                            Title = "Decentralized executive system engine",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 951, DateTimeKind.Utc).AddTicks(9432)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 952, DateTimeKind.Utc).AddTicks(1490),
                            Description = "Repellendus sequi iusto fugit veritatis. Facere error nobis nam sit. Recusandae omnis at sunt et provident nihil repudiandae aliquid voluptatem. Sapiente laudantium corporis non ut sed qui. Magni odio praesentium doloribus quas maxime quaerat nostrum cum temporibus.",
                            OwnerId = 1,
                            Title = "Grass-roots user-facing projection",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 952, DateTimeKind.Utc).AddTicks(1490)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 952, DateTimeKind.Utc).AddTicks(3137),
                            Description = "Harum consequatur tempora blanditiis error saepe adipisci magni et. Assumenda incidunt reiciendis voluptatibus. Error illum dolores ut dignissimos. Et odit optio earum aspernatur ratione. Dolorem voluptatem perferendis similique.",
                            OwnerId = 2,
                            Title = "Switchable national standardization",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 952, DateTimeKind.Utc).AddTicks(3138)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 952, DateTimeKind.Utc).AddTicks(5124),
                            Description = "Est voluptas dolorum culpa quis quasi illo aliquam voluptatem occaecati. Provident reiciendis aliquid quaerat ratione. Cupiditate et eius culpa laborum.",
                            OwnerId = 2,
                            Title = "Compatible tertiary neural-net",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 952, DateTimeKind.Utc).AddTicks(5126)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 952, DateTimeKind.Utc).AddTicks(8987),
                            Description = "Sint reiciendis at ratione autem qui blanditiis suscipit facere itaque. Eveniet sed ipsam et cum. Eaque excepturi nesciunt aperiam eaque eius id culpa. Id ad doloremque qui vitae quibusdam soluta atque. Voluptatibus beatae distinctio maiores optio atque eum assumenda dicta. Est perspiciatis fugit hic architecto ipsum et aut ut.",
                            OwnerId = 1,
                            Title = "Multi-layered clear-thinking model",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 952, DateTimeKind.Utc).AddTicks(8987)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 953, DateTimeKind.Utc).AddTicks(2951),
                            Description = "Voluptas sit est repellat possimus. Quod ut dolore reprehenderit et modi fuga ipsum magni ut. Facere necessitatibus natus quidem minus magnam qui. Repellat reiciendis odio rerum. Excepturi sint suscipit illo tempora sunt. Dolor et eos eligendi praesentium quia tempora in ad.",
                            OwnerId = 2,
                            Title = "Optimized foreground projection",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 953, DateTimeKind.Utc).AddTicks(2953)
                        });
                });

            modelBuilder.Entity("audits_.net_react_ramine.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("DailyEmailUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("daily_email_updates");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 950, DateTimeKind.Utc).AddTicks(8284),
                            Email = "test@example.com",
                            FirstName = "User",
                            LastName = "Test",
                            Password = "password",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 950, DateTimeKind.Utc).AddTicks(8287)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 950, DateTimeKind.Utc).AddTicks(8324),
                            Email = "test2@example.com",
                            FirstName = "User",
                            LastName = "Test 2",
                            Password = "password",
                            UpdatedAt = new DateTime(2022, 10, 11, 15, 41, 34, 950, DateTimeKind.Utc).AddTicks(8324)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}