// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using audits_.net_react_ramine.Data;

#nullable disable

namespace audits_.net_react_ramine.Migrations
{
    [DbContext(typeof(AuditsDbContext))]
    [Migration("20221008204306_IntialMigration")]
    partial class IntialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("audits_.net_react_ramine.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Corporis sit ratione quia minima. Quasi voluptatum tempora temporibus et atque quis nesciunt. Voluptas similique est eum id numquam ducimus quis. Eum laborum maxime aut aperiam velit. Doloremque vero sed velit libero.",
                            OwnerId = 1,
                            Title = "Right-sized reciprocal adapter",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quia vel rerum consequatur. Aliquam qui sed fugiat et nostrum. Labore explicabo consequatur reiciendis laboriosam optio sint facilis. Illum qui quod eos. Excepturi provident aut aut numquam voluptatibus.",
                            OwnerId = 2,
                            Title = "Down-sized national open system",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Alias a rerum quasi voluptates. Repellat excepturi quasi amet dolore amet veritatis facere et. Dolor ullam rem non accusantium necessitatibus dolores alias.",
                            OwnerId = 1,
                            Title = "Compatible 24 hour migration",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hic soluta eum commodi qui autem quae et. Et consectetur odit minus. Odit corrupti in nihil harum aliquam omnis. Sed et sint officiis autem voluptatem sequi. Enim enim fugit ab molestiae id hic.",
                            OwnerId = 1,
                            Title = "Customizable incremental strategy",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Et rerum assumenda veritatis qui qui et nostrum delectus nihil. Dolor rerum quaerat neque. Est quae maxime accusamus maiores quia expedita ab fugit odit. Eius iure dolorem minus sunt. Quod ipsum omnis itaque ratione officiis ut ea ad ea.",
                            OwnerId = 1,
                            Title = "Networked human-resource firmware",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hic aliquid et molestiae et. Dolorum ipsum magnam eius maiores. Qui voluptatum cumque ad fugiat itaque aliquam. Tenetur qui eveniet voluptatibus quam reiciendis eligendi. Quos voluptatem exercitationem quam sunt inventore earum tempore placeat ut. Suscipit assumenda veritatis ex sunt et.",
                            OwnerId = 1,
                            Title = "Pre-emptive discrete open system",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aut eos est in voluptatem eos natus quia. Et quo distinctio impedit molestias libero suscipit eveniet neque. Eum numquam perspiciatis omnis ex alias est et. Sit praesentium laborum atque nobis nihil voluptatem odio rerum. Qui voluptas cum tenetur omnis at explicabo velit dolores.",
                            OwnerId = 2,
                            Title = "Horizontal methodical knowledge user",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Consequatur veritatis doloremque molestiae officiis omnis et. Fugiat doloremque molestiae eum qui et consequatur aut sunt consectetur. At soluta odio debitis ut amet recusandae nulla voluptas placeat. Blanditiis itaque quo quibusdam sapiente ut quae.",
                            OwnerId = 1,
                            Title = "Optimized real-time knowledge base",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eum distinctio et odio veniam. Earum est omnis voluptatem. Mollitia aut eos rerum totam alias autem fugiat. Ullam in ab enim.",
                            OwnerId = 2,
                            Title = "Open-source modular help-desk",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dolorem distinctio delectus numquam. Culpa aut provident voluptatem repellat sunt tempora. Odio quia quisquam et quam quisquam nulla esse. Molestiae ullam velit qui accusantium a vero non. Accusamus distinctio assumenda occaecati non saepe provident omnis ut aspernatur.",
                            OwnerId = 2,
                            Title = "Reactive static concept",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("audits_.net_react_ramine.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("DailyEmailUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("daily_email_updates");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test@example.com",
                            FirstName = "User",
                            LastName = "Test",
                            Password = "password",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test2@example.com",
                            FirstName = "User",
                            LastName = "Test 2",
                            Password = "password",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
